### ISSUE TITLE
Some "Help" list items have weird spacing

### ISSUE THREAD

**Issue by barbeau** [barbeau/gpstest#107]
**Summary:** 

If you open the Help menu via 3 dots menu button and then "Help", some of the list items have strange spacing.  For example, in the below screenshot from a Samsung Galaxy S8+ w/ Android 8.0 beta the GNSS list looks fine but the "Acknowledgments" section is off:

![image](https://user-images.githubusercontent.com/928045/35697204-8506165c-0757-11e8-88f9-64bf61282584.png)

**Steps to reproduce:** 

1. Launch app
1. Tap on 3 dots for overflow menu
1. Tap "Help"
1. Scroll to bottom

**Expected behavior:** 

List items should appear evenly spaced on one line like the GNSS list

**Observed behavior:** 

Some sections like "Acknowledgments" spill onto 2nd lines from bullets

**Device and Android version:** 

Samsung Galaxy S8+ w/ Android 8.0 beta

**Screenshots:** 

See above

**Comment by goldfndr** [comment]
There's also weird spacing above and to the left of the Sky View header – it should have the same spacing as the Acknowledgements header.

**Comment by barbeau** [comment]
Thanks @goldfndr!  I believe I just fixed that too.
