### ISSUE TITLE
Implement augmented reality sky view

### ISSUE THREAD

**Issue by barbeau** [barbeau/gpstest#12]
Basic concept is that you hold the device up to the sky and it shows you where satellites are positioned in the actual sky, based on your orientation and position.

We can utilize the open-source [Google Sky Map app](https://code.google.com/p/stardroid/) to implement this.

Blog about open-sourcing the project:
http://googleresearch.blogspot.com/2012/01/open-sourcing-sky-map-and-collaborating.html?m=1

Forum post about implementation details of showing star positions:
https://groups.google.com/forum/m/#!topic/google-sky-map/UKEURYGcQP8

**Comment by barbeau** [comment]
We could also use ARCore for this, although it's only supported on newer devices.

There isn't currently a location-oriented mode to ARCore, but here's an issue for the feature request that includes an early implementation:
https://github.com/google-ar/arcore-android-sdk/issues/119

See commit here:
https://github.com/inio/arcore-android-sdk/commit/e829c05cef0b42f882a7b896e41f66f311fffb71

**Comment by goldfndr** [comment]
[GNSS View](https://play.google.com/store/apps/details?id=com.nec.android.qzss.gnssview) can be used to show what this might look like. (It apparently downloads positions and displays them for arbitrary locations, so it includes satellites that the GNSS receiver isn't actually receiving.)

**Comment by barbeau** [comment]
Here's a Unity ARCore implementation of shooting stars that might be useful:
https://github.com/FusedVR/ARCore-Shooting-Star

**Comment by barbeau** [comment]
This might be useful, need to look into it:
https://io.google/2022/program/fc42307b-3b0f-4925-bfea-99499ba08088/

**Comment by barbeau** [comment]
Not stale

**Comment by gdt** [comment]
FWIW, I'm -1 on implementing features that require proprietary OS components.  So if it won't work on lineage/calyx/etc. and if it won't work in the fdroid build, I see it as not a good thing to add.

**Comment by barbeau** [comment]
Not stale
