### ISSUE TITLE
Proposal for logo new logo design 

### ISSUE THREAD

**Issue by jbeguna04** [barbeau/gpstest#135]
Hi good day! I would like to ask for your permission to propose a new designs of logo in your application/project. This issue is not saying that your current logo is unsatisfactory, I would just like to propose new designs. Hoping for your positive response Thank You!

**Comment by barbeau** [comment]
@jbeguna04 I'm always open to new ideas, although I just put together a new logo for the v3 release that is rolling out to production now.  You can opt-in to the beta testing group to see it on your device at:
https://play.google.com/apps/testing/com.android.gpstest

Here's a large version of it:
![web_hi_res_512](https://user-images.githubusercontent.com/928045/36711620-5ce2ff82-1b52-11e8-936e-53db1144d330.png)

**Comment by jbeguna04** [comment]
Thank you for the quick reply. I understand that

**Comment by barbeau** [comment]
Sure!  I'll close out this issue for now just for housekeeping, but if you really want to put something together feel free to post proposals on this thread.  I'd definitely welcome any other UI/UX design suggestions for the app itself as well, but please open new issues for those.
