### ISSUE TITLE
Google Play "Released on" date shows Dec 31, 1969

### ISSUE THREAD

**Issue by wesinator** [barbeau/gpstest#136]
**Summary:** 
Not a big deal, but the "Released on" date displayed in Google Play is `Dec 31, 1969`

**Device and Android version:** 
Samsung, 6.0.1

**Comment by barbeau** [comment]
Ha, good eye! Looks like a bug in Google Play. The original release of this app was uploaded to Google Play (at the time Android Market) waaaaay early, circa 1.5 Cupcake release as a reference implementation for OEMs and developers. I'm guessing Google Play isn't reading this old value correctly. I'm closing this as there isn't anything I can do about it, and it's kind of a fun conversation piece :).
