### ISSUE TITLE
Output when sharing position

### ISSUE THREAD

**Issue by paulle** [barbeau/gpstest#147]
Sharing position with gpstest creates a link to goolemaps wit the actual position.
It would be more user friendly with an additional output in the form:
Longitude: xxxxxxxxxxx
Latitude: xxxxxxxxxx
It would it make a little bit mor comfortable for people using other map services (OSM, Here etc.) or using maps locally stored for offline use (OSMand).
Aside from this gpstest is an excellent app, the only one (I tested a few) showing reliable the Galileo satellites.

**Comment by barbeau** [comment]
Thanks @paulle! I actually reopened your other issue at https://github.com/barbeau/gpstest/issues/146 so I'm going to close this as a duplicate.
