### ISSUE TITLE
one more device supporting Galileo (not listed in the FAQ)

### ISSUE THREAD

**Issue by paulle** [barbeau/gpstest#148]
One more device is supporting Galileo and is not listed in the FAQ.
The Sony xperia XZ2 (android 8.0) is supporting Galileo too and works nice with gpstest.

**Comment by barbeau** [comment]
Thanks @paulle!  Could you please share a screenshot?

**Comment by paulle** [comment]
![screenshot_20180527-104400](https://user-images.githubusercontent.com/4852079/40584116-fd970f9c-619b-11e8-89f4-1776e32bdff8.png)
![screenshot_20180527-104501](https://user-images.githubusercontent.com/4852079/40584117-fdb514ec-619b-11e8-8bd5-37f4fc50b4ce.png)

**Comment by paulle** [comment]
Above screenshots Sony xperia XZ2
