### ISSUE TITLE
Sky chart background should be dark in dark theme

### ISSUE THREAD

**Issue by goldfndr** [barbeau/gpstest#151]
**Summary:** 

The sky chart's background is light when using a dark theme but should be dark.

**Steps to reproduce:** 

1. Start Google flavor of app.
2. Settings -> Use Dark Theme=ticked.
3. Restart app.
4. Sky (from hamburger menu).

**Expected behavior:** 

Show dark theme chart (the area inside the giant circle at the top). The background color of the chart *could* be the same as the legend's background. Or it could be black and the borders of the shapes could be a light color.

**Observed behavior:** 

See light theme sky chart.

**Device and Android version:** 

Moto G (2013), KitKat 4.4.4, stock ROM with some Xposed modules, Google Play Services 12.2.1

**Screenshots:** 

Available upon request.

**Comment by barbeau** [comment]
I started implementing this a bit along with the avg C/N0 indicator, but it ends up being incredibly messy with a lot of boiler-plate code, as the sky circle is generated entirely programmatically.  I may take a look at this in the future but for now I'm going to focus my (limited) time on other items.
