### ISSUE TITLE
Sky Avg SNR chart not colored in KitKat

### ISSUE THREAD

**Issue by goldfndr** [barbeau/gpstest#152]
**Summary:** 

The Sky activity's Avg SNR chart should show a gradient (like in screenshot) insead of a uniformly dark rectangle.

**Steps to reproduce:** 

1. Start Google app.
2. Sky (from hamburger menu).
3. Scroll down as needed until Avg SNR chart is visible.

**Expected behavior:** 

Show a gradient in the interior of the Avg SNR chart.

**Observed behavior:** 

See uniformly dark interior of the Avg SNR chart, regardless of Use Dark Theme ticked.

**Device and Android version:** 

Moto G (2013), KitKat 4.4.4, stock ROM with some Xposed modules, Google Play Services 12.2.1

**Screenshots:** 

Available upon request.

**Comment by barbeau** [comment]
Thanks for flagging this! My last KitKat test device died a while back so I'll see if I can repro via emulator. If possible could you share a screenshot?

**Comment by goldfndr** [comment]
Sure. Here you go.

![light_missing_snr](https://user-images.githubusercontent.com/173956/41510995-35c7fe3e-7223-11e8-83ba-6e6646014dd0.png)
![dark_missing_snr](https://user-images.githubusercontent.com/173956/41510996-3ad9ef9a-7223-11e8-93f8-f03d0117607f.png)

**Comment by goldfndr** [comment]
Also, that tick mark for 15 looks suspiciously non-centered.

**Comment by barbeau** [comment]
Thanks! Yeah, not sure what's going on with the 15 tick, will take a look.

**Comment by goldfndr** [comment]
In gps_sky_signal_meter.xml, the margins for the tick marks (sky_legend_cn0_\*) appear to be: 2, 25, 44, 63, 2, 98, 117, 136, 2. Granted, those 2s are somewhat aligned with the rectangle, but it looks to me like the space between the last two tick marks (30 and what comes before) is larger than the preceding spaces.
