### ISSUE TITLE
Add more satellite shapes

### ISSUE THREAD

**Issue by barbeau** [barbeau/gpstest#161]
**Summary:** 

I originally added constellation shapes as more GNSS constellations came available in Android devices without a long-term strategy for how these would be managed.  As a result, the triangle is over-used, currently representing:
* Galileo
* QZSS
* All SBAS

We should refresh these to add new shapes to better distinguish between these constellations.

Let's also consider IRNSS/NAVIC here too (currently ticketed in https://github.com/barbeau/gpstest/issues/105).

Here's the current plan:
* Galileo - Triangle
* QZSS - Hexagon
* All SBAS - Diamond
* IRNSS/NAVIC - Oval, Octagon (Octagon is currently hard to differentiate from a circle), or Square with Triangle corners - To be solved in #105 

Current screenshot is below:

![image](https://user-images.githubusercontent.com/928045/42004754-373dab3c-7a3f-11e8-9f51-dc9e8ed53a0d.png)

**Steps to reproduce:** 

1. From nav drawer tap on Sky view
1. Look at Legend, or if you have a device that supports many constellations look at the sky view with live satellite positions

**Expected behavior:** 

Have unique shapes per satellite constellation

**Observed behavior:** 

Triangle is used for:
* Galileo
* QZSS
* All SBAS

We don't yet have a shape for IRNSS/NAVIC (see https://github.com/barbeau/gpstest/issues/105).

**Device and Android version:** 

N/A

**Comment by goldfndr** [comment]
Some comments:

* Maybe use a square diamond (square rotated 45°) or lozenge (diamond with squeezed middle) for Galileo? If you want approximately the same area as GLONASS, extend height to about 1.4× (sqrt(2)), but perhaps GLONASS should be reduced in size to more closely match GPS's area. 
* Maybe upside-down triangle for QZSS? 
* IRNSS/NavIC will eventually happen.
* I haven't yet seen a screenshot with an SBAS satellite having elevation or azimuth. Given one's orbit, should these values be expected?

**Comment by barbeau** [comment]
>Maybe use a square diamond (square rotated 45°) or lozenge (diamond with squeezed middle) for Galileo?

I think I'm going to use the triangle for Galileo, as it's easily distinguishable from other shapes and for many devices a number of Galileo devices will dominate the display.  QZSS has far fewer satellites and could be one of these other "stranger" shapes.

>IRNSS/NavIC will eventually happen.

Yes, thanks for bringing that up.  That's currently ticketed in https://github.com/barbeau/gpstest/issues/105, and I just added a note to the top post as well.

>I haven't yet seen a screenshot with an SBAS satellite having elevation or azimuth. Given one's orbit, should these values be expected?

Good question. Short answer is I don't know - I haven't seen an SBAS with elevation or azimuth yet either.  I'd welcome info from someone that might have more knowledge on that.

In the case of GPSTest, though, the Android GnssStatus API definitely allows SBAS satellite objects to have elevation and azimuth, so I have to design as if that could happen.

**Comment by barbeau** [comment]
This site is useful for converting SVGs to Android vector XML:
http://inloop.github.io/svg2android/
