### ISSUE TITLE
Chinese Languages 

### ISSUE THREAD

**Issue by wangkf** [barbeau/gpstest#172]
https://github.com/wangkf/gpstest/tree/master/GPSTest/src/main/res/arrays.xml
https://github.com/wangkf/gpstest/tree/master/GPSTest/src/main/res/strings.xml
Put these two files in the **gpstest-master\GPSTest\src\main\res\values-zh-cn** folder

**Comment by barbeau** [comment]
Awesome, thanks @wangkf!  I believe the folder name should be `zh-rCN`?  This is the only way Android Studio would let me build the project, so I added it in https://github.com/barbeau/gpstest/commit/0b6c0ddd6b71e0a66b0c46917a229ff8e8e79326.

If you think this isn't right please let me know.  Also, if you'd be able to check the next beta release to make sure it looks right that would be great!

**Comment by wangkf** [comment]
You are right.
