### ISSUE TITLE
Alignment of decimal values in status view

### ISSUE THREAD

**Issue by SIRSteiner** [barbeau/gpstest#189]
**Summary:** 

At the moment all numerical values in status view aligned left instead right

**Steps to reproduce:** 

Look at status view, numerical columns ;-)

**Expected behavior:** 

aligned at the decimal point or right

**Observed behavior:** 

left alignment

**Device and Android version:** 

BQ M5, LineageOS 14.1

**Screenshots:** 

not necessary

**Comment by barbeau** [comment]
This would be nice - I'll see if I can take a look at this.
