### ISSUE TITLE
extra menupoint or tab for velocity (big numbers)

### ISSUE THREAD

**Issue by paulle** [barbeau/gpstest#201]
When riding bicycle I use my phone fixed at the handlebar. It would be nice to have an option showing the velocity with really big numbers (at least two thirds of the display), for seeing the velocity without the need to take the phone in the hands and even for seeing the numbers well in bright sunlight.

I don't know, maybe this issue is a little bit "off topic", if it is so, please excuse.

**Comment by barbeau** [comment]
@paulle Thanks for the feedback!  I'm not sure if this is something I'll implement yet, although it somewhat overlaps with #176.  I'll leave this issue open though and see what might work.

**Comment by paulle** [comment]
Thank you

Am 10. September 2018 18:47:44 MESZ schrieb Sean Barbeau <notifications@github.com>:
>@paulle Thanks for the feedback!  I'm not sure if this is something
>I'll implement yet, although it somewhat overlaps with #176.  I'll
>leave this issue open though and see what might work.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/barbeau/gpstest/issues/201#issuecomment-419981551

-- 
K-9 Mail gesendet.

**Comment by goldfndr** [comment]
In the meantime, you can work around this missing feature with [SpeedMeter](https://github.com/flyingrub/SpeedMeter) or almost any [heads up display app](https://play.google.com/store/search?q=heads%20up%20display&c=apps). (Admittedly, SpeedMeter is closer to 1/3 of the display.)

**Comment by barbeau** [comment]
@paulle Ok, great.  I added a comment to #176 to capture the topic of this issue, and will close out this issue.
