### ISSUE TITLE
osmdroid - Map view is sometimes blank

### ISSUE THREAD

**Issue by paulle** [barbeau/gpstest#208]
The map view within GPStest is only showing a white space (some times with pin-point, most times without it).
edit: when I switch to map view, for less than a second there is a map. but time is too short for a screenshot.
sony xz2, android8.0, GPStest 3.20 from f-droid
![screenshot_20180824-160929](https://user-images.githubusercontent.com/4852079/45569758-ce298980-b860-11e8-8e46-6981adf9346f.png)
![screenshot_20180914-195010](https://user-images.githubusercontent.com/4852079/45569759-ce298980-b860-11e8-9135-b990c4434b51.png)

**Comment by paulle** [comment]
![screenshot_20180915-105207](https://user-images.githubusercontent.com/4852079/45584578-a96ff900-b8d6-11e8-8e46-3b55c617af5d.png)
That's the map showing less than a second if I switch to map view.

**Comment by paulle** [comment]
@barbeau Thank you for your answer, and yes i n my case, if I pan around it loads slowly too, sometimes complete sometimes the map isn't complete.
My personal workaround for the moment is, pan around and waiting a little bit, or in other cases I use OSMand for map view (and navigation). OSMand has the advantage that I can have stored a lot of maps on the sd-card of my phone and I don't need data-connection or wlan (for me a great advantage when travelling).
So for me it's ok if you stay with the default OSM network tile server, because I know now that I have to pan around and wait a little bit for seeing the map. Maybe it could be useful adding a hint that one has to pan around and wait a little bit because of slow loading for avoiding that people think map view don't work (like me).
But I don't know what other users think about this point.

**Comment by barbeau** [comment]
This is fixed as part of https://github.com/barbeau/gpstest/pull/235 - Mapbox is the current tile provider for the OSMDroid version.
