### ISSUE TITLE
Change SBAS labels

### ISSUE THREAD

**Issue by nunojpg** [barbeau/gpstest#214]
I believe the current labels for SBAS are not meaningful.

For example for EGNOS the system is identified with the Luxembourg and UK flags, while that only the nationality of the commercial communications satellite used. Luxembourg and UK do not operate a SBAS system, the EU does.

Also for WAAS you picked just Galaxy 15 and Anik, and list them separately, but for Gagan you list all together.

It's much more didactic if you merge Anik and Galaxy 15 as WAAS, with Canada and US flag, and merge all the EGNOS SVs as EGNOS, with the EU flag.

Btw, for Galileo you used the project logo (not EU flag), but for the other projects you choose the country flag.

Sorry to be pedantic, I can't avoid it, but I think it's something easy to get consistent!

Thanks!

**Comment by barbeau** [comment]
@nunojpg This is really an more comprehensive version of #95, so I'm going to close this issue as a duplicate and copy your comments to that issue.
