### ISSUE TITLE
Add an option to adjust the altitude to mean altitude above sea level

### ISSUE THREAD

**Issue by barbeau** [barbeau/gpstest#22]
Currently the raw GPS altitude is shown in the app, which is the distance above the surface of the WGS84 ellipsoid in meters.

Users have requested the ability to apply an adjustment via a setting to show the altitude as the distance above mean sea level, which is more meaningful in certain use cases.

Since the distance between mean sea level and the surface of the WGS84 ellipsoid varies depending on your latitude and longitude, we will need to include a look-up table in the app (or fetch dynamically via web service) so that we can apply the proper adjustment.

More info below:
http://stackoverflow.com/questions/11168306/is-androids-gps-altitude-incorrect-due-to-not-including-geoid-height

Earth Gravitational Model 2008 (EGM2008) maps the difference in mean sea level with the ellipsoid as a function of longitude and latitude:
http://earth-info.nga.mil/GandG/wgs84/gravitymod/egm2008/egm08_wgs84.html

**Comment by barbeau** [comment]
From https://github.com/opentripplanner/OpenTripPlanner/issues/2301#issuecomment-245848551:

>I have found an implementation of the ellipsoid -> geoid transform in Geotools. It's in the gt-referencing3D module. http://docs.geotools.org/latest/javadocs/org/geotools/referencing/operation/transform/EarthGravitationalModel.html

>We should be able to easily transform coordinates all over the world using this.

**Comment by barbeau** [comment]
An Android-friendly implementation of EGM96 is here:
https://github.com/matthiaszimmermann/EGM96

**Comment by barbeau** [comment]
Looks like the proper dependency is:
`compile 'org.geotools:gt-referencing:16.0'`

However, I'm getting error when trying to sync `build.gradle`:

>Error:Could not find jai_core.jar (javax.media:jai_core:1.1.3).
Searched in the following locations:
 https://jcenter.bintray.com/javax/media/jai_core/1.1.3/jai_core-1.1.3.jar

**Comment by barbeau** [comment]
I've done a lightweight port of the GeoTools `EarthGravitationalModel` that should work on Android:
https://github.com/barbeau/earth-gravitational-model

**Comment by barbeau** [comment]
Another option is to parse geoid altitude from the NMEA strings - here is a sample grabbed from an LG G5 w/ Android 6.0.1:

~~~
1479088202003,$GPGGA,015002.0,2804.733672,N,08224.631117,W,1,06,1.1,78.9,M,-24.0,M,,*56
1479088202003,$GNGNS,015002.0,2804.733672,N,08224.631117,W,AAN,09,1.1,78.9,-24.0,,*23
1479088202003,$GPVTG,0.0,T,3.2,M,0.0,N,0.0,K,A*22
1479088202004,$GPRMC,015002.0,A,2804.733672,N,08224.631117,W,0.0,0.0,141116,3.2,W,A*05
1479088202004,$GPGSA,A,2,03,14,16,22,26,32,,,,,,,1.5,1.1,0.9*3A
1479088202004,$GNGSA,A,2,03,14,16,22,26,32,,,,,,,1.5,1.1,0.9,1*39
1479088202004,$GNGSA,A,2,66,67,77,,,,,,,,,,1.5,1.1,0.9,2*3F
1479088202006,$GPGLG,VER2,HYBRID,141116,015002.0,398,2804.733672,N,8224.631117,W,79.0,,0.0,0.0,5.0,TP,Seoul,,,0,0,,*4B
1479088202006,$GPGLG,VER2,GNSS,141116,015002.0,398,2804.733672,N,8224.631117,W,79.0,,0.0,0.0,5.0,TP,Seoul,,,0,0,,*4E
1479088203001,$GLGSV,2,1,07,66,36,151,14,77,50,000,20,67,84,309,14,78,45,264,*6F
1479088203002,$GLGSV,2,2,07,76,10,036,,79,10,237,,68,27,329,*5D
1479088203002,$GPGSV,4,1,13,03,36,302,29,14,54,075,22,16,46,194,24,22,47,281,24*75
1479088203003,$GPGSV,4,2,13,23,10,309,16,26,76,157,28,31,47,023,18,32,31,105,25*75
1479088203003,$GPGSV,4,3,13,01,04,250,,10,03,158,,25,04,036,,27,00,175,*70
1479088203003,$GPGSV,4,4,13,29,09,066,*49
1479088203003,$GPGGA,015003.0,2804.733670,N,08224.631127,W,1,06,1.1,78.5,M,-24.0,M,,*5A
1479088203004,$GNGNS,015003.0,2804.733670,N,08224.631127,W,AAN,09,1.1,78.5,-24.0,,*2F
1479088203004,$GPVTG,0.0,T,3.2,M,0.0,N,0.0,K,A*22
1479088203004,$GPRMC,015003.0,A,2804.733670,N,08224.631127,W,0.0,0.0,141116,3.2,W,A*05
1479088203005,$GPGSA,A,2,03,14,16,22,26,32,,,,,,,1.5,1.1,0.9*3A
1479088203005,$GNGSA,A,2,03,14,16,22,26,32,,,,,,,1.5,1.1,0.9,1*39
1479088203005,$GNGSA,A,2,66,67,77,,,,,,,,,,1.5,1.1,0.9,2*3F
1479088203005,$GPGLG,VER2,HYBRID,141116,015003.0,399,2804.733669,N,8224.631126,W,79.0,,0.0,0.0,5.0,TP,Seoul,,,0,0,,*43
~~~

NMEA reference for GGA strings:
http://www.gpsinformation.org/dale/nmea.htm#GGA

>Where:
* GGA          Global Positioning System Fix Data
* 123519       Fix taken at 12:35:19 UTC
* 4807.038,N   Latitude 48 deg 07.038' N
* 01131.000,E  Longitude 11 deg 31.000' E
* 1            Fix quality: 0 = invalid
  * 1 = GPS fix (SPS)
  * 2 = DGPS fix
  * 3 = PPS fix
  * 4 = Real Time Kinematic
  * 5 = Float RTK
  * 6 = estimated (dead reckoning) (2.3 feature)
  * 7 = Manual input mode
  * 8 = Simulation mode
* 08           Number of satellites being tracked
* 0.9          Horizontal dilution of position
* 545.4,M      Altitude, Meters, above mean sea level
* 46.9,M       Height of geoid (mean sea level) above WGS84 ellipsoid
* (empty field) time in seconds since last DGPS update
* (empty field) DGPS station ID number
* *47          the checksum data, always begins with *

**Comment by barbeau** [comment]
With the `Location.getAltitude()` value of `-5.0 m` displayed on the screen, I saw this NMEA sentence at the same time in Android Studio log output:

`$GPGGA,032739.0,2804.732835,N,08224.639709,W,1,08,0.8,19.2,M,-24.0,M,,*5B`

So `-5 m` is the ellipsoid altitude, and `19.2 m` is the geoid altitude (above mean sea level - the new value we want to display in the app).  `-24 m` is the offset.

**Comment by barbeau** [comment]
More info on other NMEA talker IDs:
https://github.com/mvglasow/satstat/wiki/NMEA-IDs

**Comment by barbeau** [comment]
Other NMEA references:
* http://catb.org/gpsd/NMEA.html
* https://www.trimble.com/OEM_ReceiverHelp/V4.44/en/NMEA-0183messages_GNS.html

**Comment by vkbellis** [comment]
> ```
> 1479088202003,$GPGGA,015002.0,2804.733672,N,08224.631117,W,1,06,1.1,78.9,M,-24.0,M,,*56
> 1479088202003,$GNGNS,015002.0,2804.733672,N,08224.631117,W,AAN,09,1.1,78.9,-24.0,,*23
> 1479088202003,$GPVTG,0.0,T,3.2,M,0.0,N,0.0,K,A*22
> 1479088202004,$GPRMC,015002.0,A,2804.733672,N,08224.631117,W,0.0,0.0,141116,3.2,W,A*05
> 1479088202004,$GPGSA,A,2,03,14,16,22,26,32,,,,,,,1.5,1.1,0.9*3A
> 1479088202004,$GNGSA,A,2,03,14,16,22,26,32,,,,,,,1.5,1.1,0.9,1*39
> 1479088202004,$GNGSA,A,2,66,67,77,,,,,,,,,,1.5,1.1,0.9,2*3F
> 1479088202006,$GPGLG,VER2,HYBRID,141116,015002.0,398,2804.733672,N,8224.631117,W,79.0,,0.0,0.0,5.0,TP,Seoul,,,0,0,,*4B
> 1479088202006,$GPGLG,VER2,GNSS,141116,015002.0,398,2804.733672,N,8224.631117,W,79.0,,0.0,0.0,5.0,TP,Seoul,,,0,0,,*4E
> 1479088203001,$GLGSV,2,1,07,66,36,151,14,77,50,000,20,67,84,309,14,78,45,264,*6F
> 1479088203002,$GLGSV,2,2,07,76,10,036,,79,10,237,,68,27,329,*5D
> 1479088203002,$GPGSV,4,1,13,03,36,302,29,14,54,075,22,16,46,194,24,22,47,281,24*75
> 1479088203003,$GPGSV,4,2,13,23,10,309,16,26,76,157,28,31,47,023,18,32,31,105,25*75
> 1479088203003,$GPGSV,4,3,13,01,04,250,,10,03,158,,25,04,036,,27,00,175,*70
> 1479088203003,$GPGSV,4,4,13,29,09,066,*49
> 1479088203003,$GPGGA,015003.0,2804.733670,N,08224.631127,W,1,06,1.1,78.5,M,-24.0,M,,*5A
> 1479088203004,$GNGNS,015003.0,2804.733670,N,08224.631127,W,AAN,09,1.1,78.5,-24.0,,*2F
> 1479088203004,$GPVTG,0.0,T,3.2,M,0.0,N,0.0,K,A*22
> 1479088203004,$GPRMC,015003.0,A,2804.733670,N,08224.631127,W,0.0,0.0,141116,3.2,W,A*05
> 1479088203005,$GPGSA,A,2,03,14,16,22,26,32,,,,,,,1.5,1.1,0.9*3A
> 1479088203005,$GNGSA,A,2,03,14,16,22,26,32,,,,,,,1.5,1.1,0.9,1*39
> 1479088203005,$GNGSA,A,2,66,67,77,,,,,,,,,,1.5,1.1,0.9,2*3F
> 1479088203005,$GPGLG,VER2,HYBRID,141116,015003.0,399,2804.733669,N,8224.631126,W,79.0,,0.0,0.0,5.0,TP,Seoul,,,0,0,,*43
> ```

This example from November 2016 is informative, thank you Sean for providing it.

The NMEA snippet above is missing the [DTM](https://www.trimble.com/OEM_ReceiverHelp/V4.44/en/NMEA-0183messages_GPDTM.html) sentence.

Please provide another NMEA stream example which includes [GGA](https://www.trimble.com/OEM_ReceiverHelp/V4.44/en/NMEA-0183messages_GGA.html), [GNS](https://www.trimble.com/OEM_ReceiverHelp/V4.44/en/NMEA-0183messages_GNS.html) and [DTM](https://www.trimble.com/OEM_ReceiverHelp/V4.44/en/NMEA-0183messages_GPDTM.html) sentences, and if it's convenient, from somewhere near the same location.

Kelly

**Comment by barbeau** [comment]
@vkbellis I posted more info back on the other open issue at https://github.com/barbeau/gpstest/issues/503#issuecomment-861656796. Let's resume the discussion there.
