### ISSUE TITLE
Update Dutch translation

### ISSUE THREAD

**Issue by barbeau** [barbeau/gpstest#222]
**Summary:** 

@D3nnisd I just release a new v3.2.1 beta:
https://groups.google.com/forum/#!topic/gpstest_android/mLSfDQyU2KU

Here's a direct link to all English string edits between v3.2.0 and v3.2.1:
https://github.com/barbeau/gpstest/compare/v3.2.0...v3.2.1

(**EDIT** - I tried to link directly to English `strings.xml` file in the above, but that doesn't seem to work.  So you'll need to scroll down to that file.)

If you could make sure that the Dutch translation file matches these, it would be great!

Thanks!

**Comment by D3nnisd** [comment]
On it!

I've send you a email, please check!

Op ma 8 okt. 2018 om 19:09 schreef Sean Barbeau <notifications@github.com>:
