### ISSUE TITLE
Add extra-wide Status location card layout

### ISSUE THREAD

**Issue by barbeau** [barbeau/gpstest#225]
**Summary:** 

Requested by user at https://groups.google.com/d/msg/gpstest_android/mLSfDQyU2KU/XCJO4SpQAAAJ:

>Into the window 1 there are 2 columns. Do you think it is easy to add one more column and move data from the other 2 preceding columns. If we can do this, we will earn 2 more lines to the main window with the flags. As you can see, into the place I have print the red number 1, it's empty of data.

![image](https://user-images.githubusercontent.com/928045/46706674-cb257d00-cc03-11e8-9c45-5ac78e814fda.png)

We could add another layout for extra-wide devices to move 2-ish rows up to a 3rd column in the Location card.  This would collapse the card vertically a bit to make it smaller.

**EDIT** The user was using the "small" font setting (see below), so this gets a little more complicated.  We would need to look into how font sizes are scaled in Android vs. our project settings, and if this scaling is consistent across devices.

![image](https://user-images.githubusercontent.com/928045/46749540-f51e8400-cc83-11e8-952a-108f0bbd39b3.png)

**Steps to reproduce:** 

Open app to Status screen on 1+ 5T device with "small" font setting

**Expected behavior:** 

Take advantage of the extra open space in the Location card with a 3rd column

**Observed behavior:** 

There are two columns in the Location card, and empty space to the right

**Device and Android version:** 

1+ 5T

**Comment by paulle** [comment]
mtp://%5Busb%3A001,004%5D/Interner%20gemeinsamer%20Speicher/Pictures/Screenshots/Screenshot_20181012-111841.png
I have to use my device with big font setting and the status view is cutted (in vertical view, in horizontal view all is visible). It would be nice if there is a solution even for people using the big font size without the "cuts".
