### ISSUE TITLE
no more sbas satellites available

### ISSUE THREAD

**Issue by paulle** [barbeau/gpstest#227]
No more sbas satellites available. With v3.2.2 or/and android 9 are the sbas satellites no more available.
Don't know what the reason is, because I updated to v3.2.2 from f-droid and one day later my device got the update to android 9 (sony xz2). Before I got the updates, I got the sbas satellites.
![screenshot_20181013-142042](https://user-images.githubusercontent.com/4852079/46908039-99baf300-cf1c-11e8-9b64-6e4443fab896.png)

**Comment by barbeau** [comment]
@paulle SBAS satellites showing up can be fairly transient from my experience. Give this one a little more time to see if they show up again, and check at different times of the day. If after a week or two you don't see SBAS then please reopen this issue.
