### ISSUE TITLE
Add option to stop GPS when app is in background

### ISSUE THREAD

**Issue by danburd** [barbeau/gpstest#237]
**Summary:** 

When using GPSTest with GPS on, and I navigate to the home screen or to another app, the GPS icon remains in the status bar, as if GPSTest is using GPS in the background. It will stay in the status bar indefinitely until I re-open the app and use the "switch" inside the app to turn GPS off, or until I force close GPSTest.

I do not know if the app is actually using GPS during the time that the GPS icon is in the status bar. After leaving it on for a little while and checking Android's battery status, it says that GPSTest has been "Active for 0 min" in the background.

**Steps to reproduce:** 

Open the app and switch on GPS if it isn't already on. Then, press the home button and check the status bar to see the GPS icon remains on.

**Expected behavior:** 

The GPS icon will turn off unless GPSTest is in the foreground with GPS switched on.

**Observed behavior:** 

The GPS icon in the status bar remains on unless I go into the app and switch off GPS, or force close GPSTest.

**Device and Android version:** 

Pixel 3, Android 9.0, stock. Google Play Services version 14.5.74.

**Screenshots:** 

![screenshot - gpstest](https://user-images.githubusercontent.com/4601223/48317795-8ce5f980-e5c5-11e8-84f9-2f7e861a5346.png)
Note that the GPS icon is on at the top right corner of the screen, but that the app says it has been active in the background for zero minutes.

**Comment by paulle** [comment]
Same here. Can confirm it.

**Comment by sm4rk0** [comment]
I believe this is a feature, not a bug. You can prevent/avoid it by either exiting the application via Back button, or turning the main switch off before navigating away from the app.
@barbeau Maybe a toggle in preferences would suffice?

**Comment by barbeau** [comment]
Thanks for opening this issue!  Yes, this behavior goes way back to the original v1.x version of the app before I started maintaining it, and it's never been clear to me if this is a feature or a bug.  I've leaned towards feature because no one (until now) has ever raised an issue about it, and it can help in scenarios where a user is trying to "fix" location on their device (i.e., leaving the GNSS hardware on in the background for a while can help).

@sm4rk0 Yes, I think adding a preference where the user could toggle this behavior off would be the best approach given the history.

Note that this behavior isn't consistent on all devices - on some devices Android will still kill the location listener when the app is put into the background using the home button, presumably to conserve battery life.

**Comment by danburd** [comment]
I can definitely see how this might be a feature, and I assumed that most people saw it that way, which is why I hesitated to open the issue. However, I use the home button as an "exit" button, so I'd frequently only notice after several minutes that I'd unintentionally had the GNSS on for that time.

A preference would be wonderful. Thanks for accepting the issue and for your work on the app!

**Comment by goldfndr** [comment]
>However, I use the home button as an "exit" button

Then you're doing it wrong. A couple of quotes from [Understand Tasks and Back Stack](https://developer.android.com/guide/components/activities/tasks-and-back-stack):

* When the user presses the **Back** button, the current activity is popped from the top of the stack (the activity is destroyed)
* A task is a cohesive unit that can move to the "background" when users begin a new task or go to the Home screen, via the *Home* button.

(I have no idea why the editors boldfaced Back (and, to some extent, Recents) but italicized Home; subject emphasis vs labeling conformity, I suppose.)

I'll add that the Tasker automation app commits changes when using the Back button but doesn't do much when using the Home button.

**Comment by barbeau** [comment]
>Then you're doing it wrong

Maybe so, but users really shouldn't need to be exposed to this level of technical knowledge of Android. Also, technically GPSTest isn't following the recommended practices for location management on Android here either, but again, given the app's history it's not clear if it's a feature or a bug. So I can definitely understand how this would confuse some people.

**Comment by spaetz** [comment]
Sorry for the duplicate issue, apparently I have not been searching hard enough.

I understand your arguments (and yes I am aware of the difference between suspended and exited apps), however I would suggest this needs.improvements anyway. Suspended apps are not a background service and the OS is free to kill them anytime. In recent versions of Android the trend has been towards 'never quit apps' and let the OS deal with them.
So, having a real background service (requiring a notification while running) available as a configurable option totally makes sense. Having suspended apps that can be killed by the OS at any point hang on to the GPS is not so useful IMHO.

Thanks anyway, I know now that this is the intended behavior and no bug.

**Comment by spaetz** [comment]
P.S. Just now discovered the setting which disables GPS when the app is suspendend. Perfect, thanks a bunch for GPStest!

**Comment by barbeau** [comment]
@spaetz I agree that background execution needs some improvement to catch up to current Android best practices. I opened an issue here to have GPSTest run as a foreground Service when in the background - https://github.com/barbeau/gpstest/issues/299.
