### ISSUE TITLE
No CF values on a Xiaomi MIX3

### ISSUE THREAD

**Issue by benzfish** [barbeau/gpstest#238]
Summary:

no CF shows in Xiaomi8 and MIX3. Both of them are dual frequencies phones

Steps to reproduce:

open app, and see the CF column.

Expected behavior:

GPS/GLONASS/Galileo/BDS/QZSS should show CF

Observed behavior:

nothing here on CF column, version is 3.2.7

Device and Android version:

Xiaomi MIX3 dual frequencies phone with Android P.
This issue only happens at version 3.2.7, but works well at version 3.2.6

Screenshots:

N/A

**Comment by benzfish** [comment]
Summary:

no CF shows in Xiaomi8 and MIX3. Both of them are dual frequencies phones

Steps to reproduce:

open app, and see the CF column.

Expected behavior:

GPS/GLONASS/Galileo/BDS/QZSS should show CF

Observed behavior:

nothing here on CF column, version is 3.2.7

Device and Android version:

Xiaomi MIX3 dual frequencies phone with Android P.
This issue only happens at version 3.2.7, but works well at version 3.2.6

Screenshots:

N/A

**Comment by brucechase** [comment]
I have a Mi8.  Before I did an update to the operating system, the phone provide no CF values.  After I went through the hassle of upgrading to Android Pie (version 9) Beta, I found that the CF values are now filled in.  I believe that Xiaomi will be making the Android Pie version available for automatic updates in the next month or so when it is off Beta version.

**Comment by benzfish** [comment]
@barbeau sorry. i must make a mistake. i tried both of the apks with different version. both of them could show CF now. sorry.
