### ISSUE TITLE
Add $GNGGA NMEA sentence as MSL and geoid separation source

### ISSUE THREAD

**Issue by whyneedausername** [barbeau/gpstest#253]
**Summary:** 

New snapdragon android use $GNGGA instead $GPGGA, so the MSL level in gpstest show blank.

Ref:
https://navspark.mybigcommerce.com/content/NMEA_Format_v0.1.pdf

**Device and Android version:** 

Nokia 7 Android 9

**Comment by barbeau** [comment]
Thanks @whyneedausername!  Could you share some actual $GNGGA NMEA sentences from your device?  I like to include actual data from real devices in the unit tests.

See how to log them at https://github.com/barbeau/gpstest/blob/master/LOGGING.md.

**Comment by whyneedausername** [comment]
$GNGGA,114926.00,3206.341435,N,11850.092448,E,1,11,0.9,19.9,M,2.2,M,,*7E

**Comment by barbeau** [comment]
Actually, looking now, I see both sentence types on a Samsung Galaxy S8+ (Qualcomm) with Android 8.0:

~~~
$GPGGA,172803.00,2803.204343,N,08225.993046,W,1,00,1.1,29.0,M,-24.8,M,,*6E
$GNGGA,172814.00,2803.208136,N,08225.981423,W,1,08,1.1,-19.7,M,-24.8,M,,*5F
$GNGGA,172815.00,2803.209182,N,08225.983452,W,1,08,1.1,-28.8,M,-24.8,M,,*59
$GNGGA,172816.00,2803.209922,N,08225.985192,W,1,08,1.1,-19.8,M,-24.8,M,,*55
$GNGGA,172817.00,2803.210483,N,08225.986317,W,1,08,1.1,-7.9,M,-24.8,M,,*68
$GNGGA,172818.00,2803.211078,N,08225.986857,W,1,07,1.1,-1.8,M,-24.8,M,,*61
~~~

This could explain why devices aren't showing frequent Alt MSL updates - it's broadcasting a single GPGGA sentence, and then updates using GNGGA.
