### ISSUE TITLE
Show Galileo flag for new satellites when using legacy GpsStatus API

### ISSUE THREAD

**Issue by Giolly90** [barbeau/gpstest#258]
**Summary:** 
What I previously mentioned with regard to satellite n.331 is now confirmed: I observed the same behaviour for another satellite of the Galileo costellation which has gone available yesterday. It is satellite n.336 aka Galileo-FOC FM19 "Tara". (PRN E36 is the code where to look the number displayed in GPSTest App, where Galileo satellites get the number 3+PRN ==> 336 in this case).

![cattura](https://user-images.githubusercontent.com/46520205/52624540-3ed7df00-2eaf-11e9-8807-2865a3730d2a.PNG)

Please find mentioned reference here: https://en.wikipedia.org/wiki/List_of_Galileo_satellites

Also in this case flag is missing and I am sure the same behaviour will be observed for the other newely activated satellites: 313, 315 and 333 (I'll provide evidences asap).

![screenshot_20190212-082807](https://user-images.githubusercontent.com/46520205/52624587-5a42ea00-2eaf-11e9-9b6c-47494d840178.jpg)

Please if possible add EU flag to this new series of satellites.
Let me know also about your decision whether changing the Galileo symbol with the EU flag, here is another example which I want to bring in support of my request: see that the difference is not consistent

![2](https://user-images.githubusercontent.com/46520205/52624379-e99bcd80-2eae-11e9-9af8-ffbd8cf6cc62.jpg)

Thank you,

**Comment by Giolly90** [comment]
Satellite 331 is Galileo-FOC FM18 "Irina" 3-31

**Comment by barbeau** [comment]
@Giolly90 Apparently this is a fairly widespread issue with Galileo and some receivers not properly registering the new SVs:
https://www.gsc-europa.eu/news/informative-note-about-galileo-svids-tracking

Please reach out to your device manufacturer and ask them to fix this.  Thanks!

Re: EU flag - I plan to make the change.

**Comment by barbeau** [comment]
@Giolly90 I forgot to ask one question - can you please make sure "Use GNSS APIs" setting in GPSTest is checked?

Looks like you might see this on some devices if you uncheck this setting:
https://groups.google.com/d/msg/gpstest_android/pjZV80hlbwI/Pj1GPzg9BQAJ

**Comment by Giolly90** [comment]
@barbeau thanks for suggestion and sorry for late reply, but I was testing a bit. I checked the mentioned option and now the phone is correctly recognizing all satellites! (At least I have evidence of 331 and 333, but I think also 336 will be ok).

BTW I noticed that enabling GNSS APIs the numbering is different and the first 3 is omitted.

Anyway I think this finally solved the issue! (I also opened a fix request on OnePlus page, let's see what happens).

Let me know of the changing EU flag request ;)

**Comment by barbeau** [comment]
@Giolly90 Good to hear!  Sorry, I assumed you had the default settings for the app, and I didn't realize that this would show up in this way from the legacy API until Lodro posted in the Google Group.  I do have control over the way the Galileo flag matching happens on the legacy API, so I'm going to re-open this issue so I can fix that.  You can close the OnePlus issue and just say that you observed this in an app when a setting was changed to use the legacy GpsStatus API, instead of the newer GnssStatus API.

Re: EU flag - see https://github.com/barbeau/gpstest/commit/3dd3def05027e8a2d91b755f6c1d663183bbcdc0 😉

**Comment by Giolly90** [comment]
Great! Thanks for your commitment

**Comment by barbeau** [comment]
Including https://github.com/barbeau/gpstest/issues/264 and https://www.gsc-europa.eu/news/informative-note-about-galileo-svids-tracking, here's the total list that needs to be added for Galileo:
* 331
* 332
* 333
* 334
* 335
* 336
