### ISSUE TITLE
Add distinction for GLONASS satellites (vs. U.S. Navstar)

### ISSUE THREAD

**Issue by barbeau** [barbeau/gpstest#26]
We could add an asterisk next to the PRN in the sats list to mark GLONASS sats, and could draw the Sky view GLONASS sats as triangles instead of circles.

One item of question - is the mapping of GLONASS satellites to PRN values constant / standardized?  PRN is specific to U.S. Navstar system, but a specific ID for GLONASS sats seems to be mapped to this value, based on results from Samsung Galaxy S3.

No response yet to [my GIS Stack Exchange post about this](http://gis.stackexchange.com/questions/65412/is-there-an-industry-standard-official-mapping-of-glonass-satellites-to-prn-va).

**Comment by andronov-alexey** [comment]
According to the [new](https://developer.android.com/reference/android/location/GnssStatus#getSvid(int)) Android location API:

> 93-106 as the frequency channel number (FCN) (-7 to +6) plus 100. i.e. encode FCN of -7 as 93, 0 as 100, and +6 as 106

shouldn't we replace
```
} else if (prn >= 65 && prn <= 96) {
     return GLONASS;
}
```
with
```
} else if (prn >= 65 && prn <= 106) {
      return GLONASS;
}
```
?
