### ISSUE TITLE
Add support for CDMA L1 and L3 for GLONASS

### ISSUE THREAD

**Issue by barbeau** [barbeau/gpstest#264]
**Summary:** 

Looks like the Xiaomi Mi 9 has support for the new GLONASS CDMA L1 signal based on the screenshot from a video review shown here:
https://groups.google.com/d/msg/gpstest_android/6v9cTi1iT-s/L9nr4NlGCAAJ

From https://gssc.esa.int/navipedia/index.php/GLONASS_Future_and_Evolutions:

>The future GLONASS K2 satellites will feature four additional CDMA signals along the original FDMA signals. Two of them are obfuscated signals located at 1242 MHz (L2 band) and 1575.42 MHz (L1 band) for military uses and the other two are *open signals located at 1575.42 MHz (L1 band) and 1207.14 MHz (L3 band) for civil uses*.

We should add GLONASS CDMA L1 and L3 support.

**Steps to reproduce:** 

Run GPSTest on Xiaomi Mi 9

**Expected behavior:** 

Show L1 values for GLONASS in the CF column

**Observed behavior:** 

The raw frequencies are shown instead - `1575.420`

**Device and Android version:** 

Xiaomi Mi 9

**Screenshots:** 

From https://groups.google.com/d/msg/gpstest_android/6v9cTi1iT-s/L9nr4NlGCAAJ:

![image](https://user-images.githubusercontent.com/928045/54002662-6bcd8980-411d-11e9-8a2d-8b9be9898b72.png)

**Comment by ValZapod** [comment]
@barbeau That is strange. I suppose glonass only support CDMA on E5b (they call it L3), and support of CDMA on L1 (1575.42) and L2 and will be only in https://en.wikipedia.org/wiki/GLONASS-K2 series of setellites...
