### ISSUE TITLE
Can't save Accuracy ground truth for locales with commas

### ISSUE THREAD

**Issue by uli-on** [barbeau/gpstest#274]
In order to enter my location on the Accuracy screen I tapped the map and on saving got an error re formatting of the values ("must be in decimal degrees"). Obviously, the app expects dots where my Android local default automatically puts commas: After replacing the commas with dots I could save alright.

Android 6 by Motorola
GPSTest 3.3.0

**Comment by barbeau** [comment]
Thanks for reporting this! I'll get it fixed.

**Comment by barbeau** [comment]
@uli-on I just pushed v3.3.1 release to Google Play beta testing group, which should include a fix for this issue.  Could you please give it a try and let me know?

**Comment by uli-on** [comment]
Yup, commas do work now.
