### ISSUE TITLE
Russian translation

### ISSUE THREAD

**Issue by jabozksl** [barbeau/gpstest#276]
i hope it works

[russian.zip](https://github.com/barbeau/gpstest/files/3087282/russian.zip)

**Comment by barbeau** [comment]
Thanks @jabozkzks!  If you can comment "Yes I agree" in this thread to the CLA that is here:
https://gist.github.com/barbeau/6c075d0118ad00bdb307442fe43ace30

...I can manually add these files to Transifex, which is where translations will be managed going forward.

**Comment by barbeau** [comment]
@jabozksl Friendly ping - do you agree to the CLA above for contributing the Russian translation?

**Comment by barbeau** [comment]
@jabozksl Great!  I've uploaded them here:
https://www.transifex.com/sean-barbeau/gpstest-android/language/ru/

From now on, you can use Transifex to do the translation, which should make it much easier.

Please take a look at the Transifex link - I think there are a few strings that were added after you did your initial translation.  If you can add this via Transifex I'll then download and load them into the app for testing.

**Comment by barbeau** [comment]
@jabozksl Thanks for working on this! Here's a version to test that includes the Russian strings:
https://www.dropbox.com/s/abry1x44hz7eufh/GPSTest-google-debug.apk?dl=0

Could you please work on shortening some of the strings?  You can see that even on a wide device like the Samsung Galaxy S8+ some of the strings are too long and cause wrapping, overlapping, or pushing values off-screen:

![image](https://user-images.githubusercontent.com/928045/57472942-8cac7b00-7243-11e9-9e7c-4482b5b9b9f6.png)

**Comment by jabozksl** [comment]
Hi, I've made some changes based on your screenshot, because the app, which I got from dropbox, doesn't show interface in Russian. But German interface works well as I tested on my devices.

**Comment by barbeau** [comment]
@jabozksl What Android system locale (language) is selected on your device?  The Russian translation should be showing up by default within the app if you have the Russian language set system-wide on your device.  

When testing the Russian translation you should either change your Android system locale to "Russian" in your main Android system Settings menu, or use the new GPSTest app Setting for "Language" to change to Russian.

**Comment by jabozksl** [comment]
Yep, locale is set to Russian and I can't find any "Language" section in Settings of GPSTest. Here are some screenshots
![sssssss](https://user-images.githubusercontent.com/49700159/57497717-7bb24700-72e1-11e9-8792-ef71fd1425be.jpg)

**Comment by jabozksl** [comment]
And here is the MD5 of apk, which I've downloaded here
b3beb65052a0d9fa2880ed6c32e9e931  GPSTest-google-debug.apk

**Comment by barbeau** [comment]
Ok - could you please try uninstalling your current version and install this one:
https://www.dropbox.com/s/z7q9jcmdqp6pp87/GPSTest-google-debug.apk?dl=0

You should see the Language setting in GPSTest under the "Use Dark Theme" option in Settings - if you don't please let me know.

**Comment by jabozksl** [comment]
Got it, but still no Russian or even German now
![S90510-07593120](https://user-images.githubusercontent.com/49700159/57503737-246ca080-72fa-11e9-85a4-62d6cadde1eb.jpg)

**Comment by barbeau** [comment]
Alright - let me take a closer look at what's going on

**Comment by barbeau** [comment]
@jabozksl Here's a screenshot of the latest Russian translation on a Samsung Galaxy S8+:

![image](https://user-images.githubusercontent.com/928045/57716208-75f09480-7646-11e9-898a-8240b0cc5b8a.png)

Closer, but we still need to trim off characters to avoid the top right column from extending off the page and the column headers in the 2nd card to get the headers to align right with the columns.

Please try this APK, which should include the Russian language translation and option to change locales:
https://www.dropbox.com/s/vmug0ixkavm375u/GPSTest-Russian.apk?dl=0

**Comment by barbeau** [comment]
Also, on the Accuracy screen, would it be possible to reduce the summary text to one line so the bottom of the button isn't cut off?  It's currently cut off because the summary text overflows to two lines:

![image](https://user-images.githubusercontent.com/928045/57718153-adf9d680-764a-11e9-956b-1dccf4166f07.png)

**Comment by jabozksl** [comment]
Done. It must look much better now.

**Comment by barbeau** [comment]
@jabozksl Thanks, that's much better!

![image](https://user-images.githubusercontent.com/928045/57795742-b74f7580-7714-11e9-9fa3-b20830d1ebeb.png)

I'm going to close this issue and will work on pushing out a new beta with the translation.
