### ISSUE TITLE
Show Status details in Sky view

### ISSUE THREAD

**Issue by lbdroid** [barbeau/gpstest#289]
Nor, for that matter, is the cn0 indicator, which is more or less just a summary of what is already visible in the skyview.

It would be much more useful to have status details visible along with the skyview - lat, lon, alt, dop, etc.

I'd suggest a popup for the legend/cn0. Tap in the skyview to bring it up, tap out of the popup to dismiss it.

**Comment by barbeau** [comment]
@lbdroid Thanks for the feedback!  I'll consider this when working on new features.
