### ISSUE TITLE
Shorten Czech translation

### ISSUE THREAD

**Issue by barbeau** [barbeau/gpstest#294]
**Summary:** 

@LLZN on the Czech translation, after you get a fix the top right column on the Status page hangs off the edge of the screen - see below on a Samsung Galaxy S8+:

![image](https://user-images.githubusercontent.com/928045/57718624-c3bbcb80-764b-11e9-95b8-1eb86b5cbf3d.png)

Also, on the Accuracy screen, could you try to reduce the summary text to one line so that it doesn't push the button off the bottom of the card?

![image](https://user-images.githubusercontent.com/928045/57718738-0c738480-764c-11e9-87ba-b353c158bb76.png)

Could you please try and shorten some of these strings using Transifex to avoid cutting off the content?

Thanks!

**Comment by LLZN** [comment]
FIX Czech translation

út 14. 5. 2019 v 19:28 odesílatel Sean Barbeau <notifications@github.com>
napsal:

**Comment by barbeau** [comment]
@LLZN Thanks!  That fixed the "Accuracy" screen, and "Status" is better.  But, "Status" width still needs to be reduced by a few characters:

![image](https://user-images.githubusercontent.com/928045/57796074-80c62a80-7715-11e9-87b2-9c2f1e260110.png)

I know it's a challenge but just try to get something that still makes sense but fits.  If the abbreviation needs additional explanation please add this to the `help_text` string.

**Comment by LLZN** [comment]
fix czech translation

Dne st 15. 5. 2019 19:31 uživatel Sean Barbeau <notifications@github.com>
napsal:

**Comment by barbeau** [comment]
Thanks @LLZN!  That's definitely better.  If you can shave another character off that would be ideal, but if not it's ok as-is too:

![image](https://user-images.githubusercontent.com/928045/58035494-e68c2b00-7af6-11e9-9ebe-2ac26ed49ce6.png)

**Comment by goldfndr** [comment]
@barbeau Unless there's a language in which the translation of "time" is longer than the translation of "accuracy" and other texts, or you anticipate other lengthy values, the space between columns 2 (Lat/Long values) and 3 (Time, abbreviation of TTFF) can be eliminated without fear of legibility impacts.

Or perhaps not -- I don't know if TableLayout permits varying column spacing. Perhaps setting the second column to shrinkable would work, as the last digit (or degree symbol) of the coordinates would rarely be used?

**Comment by LLZN** [comment]
Hello, if I changed the phrase "Přesn. (H/V)" to "Přesnost", it would
shorten the characters.  But then the expression would be identical to
horizontal accuracy.  It is virtually impossible to reduce the number of
characters in the Czech language without losing any meaning.  Thank you L.

Dne po 20. 5. 2019 18:01 uživatel Sean Barbeau <notifications@github.com>
napsal:

**Comment by barbeau** [comment]
@LLZN That's fine, we can leave it as-is.

@goldfndr Good idea, I'll look at tweaking the layout.  It's been a while since I touched that, if ever...
