### ISSUE TITLE
Add a "Satellite filter" feature

### ISSUE THREAD

**Issue by ammarraisafti** [barbeau/gpstest#298]
# Components
The following are the feature components that I want to recommend:

- Satellite filter

Provide options for displaying GPS, displaying GLONASS, displaying GALILEO, BEIDOU shows, QZSS shows, SBAS shows, and shows without being noticed.

# Proposal description
I propose to the GPSTest application developer to add the "Satellite Filter" feature at the top of the main display of the GPSTest application, and give users access to activate it.  Developers must modify this feature to add some interesting options that can be used by users, namely the option to display GPS, display GLONASS, display GALILEO, BEIDOU performances, QZSS shows, SBAS performances, and shows without being noticed.  And provides an icon to activate and deactivate it easily and quickly, so users can adjust it.

# Mockups / Examples
Examples of images seen after the developer added those features in the main view of the GPSTest app.
![Samsung_Galaxy-df318d77-16d5-428a-9bd8-688b2df21a23-picsay.jpg](https://res.cloudinary.com/hpiynhbhq/image/upload/v1518670536/kh9zejsnejgdiga99ovu.jpg)

![Samsung_Galaxy-df318d77-16d5-428a-9bd8-688b2df21a23-picsay.jpg](https://res.cloudinary.com/hpiynhbhq/image/upload/v1518670605/do6lpyl7mvcooa0bre3c.jpg)

![Samsung_Galaxy-df318d77-16d5-428a-9bd8-688b2df21a23-picsay.jpg](https://res.cloudinary.com/hpiynhbhq/image/upload/v1518670675/ektrkpl0zeurrtjmacza.jpg)

![Samsung_Galaxy-df318d77-16d5-428a-9bd8-688b2df21a23-picsayhaja.jpg](https://res.cloudinary.com/hpiynhbhq/image/upload/v1518670783/bm1wa9avtcsnvyccwbjx.jpg)

![Samsung_Galaxy-df318d77-16d5-428a-9bd8-688b2df21a23-picsay.jpg](https://res.cloudinary.com/hpiynhbhq/image/upload/v1518670843/teblslgkq6th7siyvkg0.jpg)

# Benefits
The "Satellite filter" feature is a very useful feature for users of the GPSTest app, as users can choose to filter some unwanted satellites while using the GPSTest app, such as enable and disable to display GPS, show GLONAS, show GALILEO, Show BEIDOU, display QZSS , display SBAS, and display Unknown, and the user can save the selection after the user selects it. And it's so awesome that users are very happy with the presence of the feature, and will invite their friends to download and install the GPSTest app, so that the users of the GPSTest app will increase with the presence of the feature, and the GPSTest app will be more interesting to use.

**Comment by barbeau** [comment]
@ammarraisafti Thanks for the feedback!  I agree, a feature to filter the visible satellites would be useful.
