### ISSUE TITLE
Two very interesting and useful new features in the GPSTest app

### ISSUE THREAD

**Issue by ammarraisafti** [barbeau/gpstest#301]
# Components
The following are the feature components that I want to recommend:

- NMEA Log
- Info

# Proposal
Propose to the GPSTest application developer to add the "NMEA Log" feature in the shortcut section of the selection, and give the user access to save the Path in the SD card to see the state and health of the satellite.

And propose to the developer of the GPSTest app to add the "Info" feature in the shortcut option, and give the user the GPS status and Information information of the G-sensor running on the android device.

# Mockups / Examples
An example image after the developer adds both features I propose in the GPSTest application selection shortcut.
![Screenshot_20180301-133023-picsay.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1520243544/lhx9nz9hlz6tmpcy8inn.png)

An example image after the developer adds the "NMEA Log" feature and gives the user access using the feature to save Path in the SD card.
![Screenshot_20180301-133023-picsayh.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1520243686/lxwzbk0egphcjigrjago.png)

An example image after the developer adds the "Info" feature and gives the user a status GPS and G-sensor information running.
![Screenshot_20180301-133023-picsayf.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1520245929/k6a0bqvrhateiu4achxd.png)

# Benefits
After the developer adds the "NMEA Log" feature and the "Info" feature in the GPSTest application, the user can perform the exact point position test
save the path in the SD card. And users can
check the results on the google map to see the state and health of the satellite. And it's amazing and useful for users, as users will get accurate information about GPS on their devices. User can save Log: save path in SD card (NMEA Log - all satellite data) using NMEA Log feature. So users can see the results on the map. And that's a big advantage. Users also get GPS status information, such as PDOP, VDOP, HDOP, and many others, and users can find the Compass Degree and G-Sensor information running on their android device.

**Comment by barbeau** [comment]
@ammarraisafti Thanks for the feedback!  It looks from the screenshot you're running a very old version of GPSTest?  Things like PDOP, VDOP, HDOP, Speed, Bearing, etc. should all appear in the top of the Status screen (if supported by your device).

I just opened this issue to focus specifically on NMEA logging - https://github.com/barbeau/gpstest/issues/303.  Note that there is currently an ad-hoc NMEA logging solution via Android Studio - see https://github.com/barbeau/gpstest/blob/master/LOGGING.md.
