### ISSUE TITLE
Add GENERAL feature in the application GPSTest

### ISSUE THREAD

**Issue by ammarraisafti** [barbeau/gpstest#304]
# Components
The following are the feature components that I want to recommend:

- General

# Proposal
proposed features "general" at the look application main gpstest, and modify the section to provide features "fundamental settings", and added features language, enabled expert mode, enable dump mode, and features extensive large file, as well as provide users access to set the feature in accordance with the desired.

# Mockups / Examples
Example image illustration after developers added features "general" in the application gpstest.

https://res.cloudinary.com/hpiynhbhq/image/upload/v1519155283/tbydkjse7h261yo3tqmt.png

https://res.cloudinary.com/hpiynhbhq/image/upload/v1519156700/vtihcycaucgrvhgrbkvy.png

https://res.cloudinary.com/hpiynhbhq/image/upload/v1519156759/vr4f5gtakdsdon8rlks1.png

https://res.cloudinary.com/hpiynhbhq/image/upload/v1519156797/kcxpvzmawbcct5kphizy.png

https://res.cloudinary.com/hpiynhbhq/image/upload/v1519156824/tj6suvrdtx2dgynrst7w.png

https://res.cloudinary.com/hpiynhbhq/image/upload/v1519156853/dbdj5y8nxtbfp3dbvvgj.png

https://res.cloudinary.com/hpiynhbhq/image/upload/v1519157363/sda34gv6kbcj1p6mxo74.png

# Benefits
The benefits of the "General" feature I propose are, the user can find the fundamental settings to change the language as desired, such as choosing to display and use the default language of the system, english, dask, deutsch and many other languages, so the user no difficulty in understanding and using the GPSTest application, the user can also set the option to enable expert mode, to set the unit bandwitch to be displayed, such as want to display the unit bits / sec, user can also enable dump mode to enable compress feature using GZIP, is very impressive and useful to users, so users feel very happy with the presence of these features, and invite other users to download and install GPSTest applications.

**Comment by barbeau** [comment]
@ammarraisafti while I appreciate the feedback and ideas in these issues, I'm getting the feeling that you're not really taking a close look at the current application before making some of these suggestions. The screenshots you're using for mockups are from very old versions of GPSTest. The app currently has a setting for changing the language. 

Could you please do me a favor and install the lastest version from Google Play or F-Droid and spend some time using it, and then use the lastest version screenshots for future suggestions?

Thanks!
