### ISSUE TITLE
Add the "Measurement Unit" feature and the "Location Services" feature in the GPS Test application

### ISSUE THREAD

**Issue by ammarraisafti** [barbeau/gpstest#305]
# Components
Gpstest is an open source application for android devices that is useful for testing GPS on devices to work or not and display real-time satellite information on an Android device, its simple appearance makes this application very easy to use, very small file sizes make this application run with  smoothly.  

<code>After using this application a few weeks to test and display real-time satellite information on an Android device, I was interested in suggesting two new features that were very important and interesting to use.</code>

The following are the feature components that I want to recommend:

- Measurement Unit
- Location Services

# Proposal description
**The following is a description of the proposal from the two feature components that I recommend:**

Add the "Measurement Unit" feature in the Display Settings section of the GPSTest application, and modify that section to add the "Select Unit" feature in it, and provide users with two choices of units that can  used, namely "metric" and "empire". 

Add the "Location Services" feature in the GNSS Settings section, and give users two options to allow GPS access, namely "when using the application" and "always".  Also add the "Location Services" feature in the top right selection shortcut section, and modify that section to give users access to the "Location Services" feature it easily and quickly.

# Mockups / Examples
Examples of images seen in the GPSTest app after the developer added the feature I proposed in the Settings Display section and the settings GNSS  and top toolbar of the app.
![Screenshot_20180219-195706-picsay.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1519046168/xffguv4jbuoc8hfrz8e6.png)

![Screenshot_20180219-195706-picsay.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1519046196/wbcopprumw7tpexfkj4c.png)

![Screenshot_20180219-231724-picsay.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1519057292/ph2lpxqg2sfagcjaslqh.png)

![Screenshot_20180219-231724-picsay.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1519057306/ulxm2ly1t9wxluguvveo.png)

![Screenshot_20180219-061812-picsay.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1518996823/evqtz1dxzqhlrgpt8lss.png)

![Screenshot_20180219-061812-picsay.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1518996919/vjx9n7xzwqwfubuorprb.png)

# Benefits
The two features that I propose for the GPSTest application are very important and interesting features to use.  Because both features will make this application more functionality.  Users can use the "Measurement Unit" feature to set the unit to display as desired, the user can choose metric and imperative units.  Users can also set "Location Services" to allow it to operate using the application or choose to always allow it to be active, and users can quickly and easily manage locations using this feature.  And that is a big advantage for users, so users will rank the best GPSTest application, and invite new users to download the GPSTest application.

**Comment by barbeau** [comment]
@ammarraisafti Please see my comment here - https://github.com/barbeau/gpstest/issues/304#issuecomment-504397463.
