### ISSUE TITLE
Screen rotation turns off satellite updates on Status screen

### ISSUE THREAD

**Issue by rick-gse** [barbeau/gpstest#310]
**Summary:** 

Using version 3.3.2 of GPSTest

Rotating screen turns off the satellites updates on the Status screen.

**Steps to reproduce:** 

Show status screen in portrait mode, satellites are updating.
Rotate screen to landscape. Satellites stop updating.

**Expected behavior:** 

Satellites should stay updating after rotation.

**Observed behavior:** 

Satellites stop updating.

**Device and Android version:** 

Google Pixel 3XL.
Android 9

**Comment by barbeau** [comment]
@rick-gse Could you include a screenshot of your Settings in GPSTest? And if you uninstall and re-install can you reproduce this every time with the default settings?

I can't reproduce this in v3.3.3 on a Samsung Galaxy S8+ w/ Android 9.  You might want to try v3.3.3 as well (rolling out to production now, but you can get it immediately if you join the beta group at https://play.google.com/apps/testing/com.android.gpstest). It has minor changes though that shouldn't impact this.

**Comment by barbeau** [comment]
Note that the resetting of satellites on Status is expected - the GPS re-initializes when you rotate the app.  So if you're in a place where it's hard to get a fix, you may need to wait a while for the satellites to re-appear.

**Comment by rick-gse** [comment]
Re-installing fixed it, so I did some testing, it's the "Stop GNSS in background" setting. When this is ON, rotation stops the updates, when it is off, rotation does not stop the updates.

![Screenshot_20190710-160336](https://user-images.githubusercontent.com/5148601/61008865-0210f680-a32e-11e9-8c2f-8965c34da012.png)

![Screenshot_20190710-160348](https://user-images.githubusercontent.com/5148601/61008867-03422380-a32e-11e9-8285-3efe1ea79ae0.png)

![Screenshot_20190710-160327](https://user-images.githubusercontent.com/5148601/61008820-e6a5eb80-a32d-11e9-9b8e-d55d2fb00e38.png)

**Comment by rick-gse** [comment]
Also ran it in the android emulator using the current code, and it did the same thing.

**Comment by rick-gse** [comment]
This seemed to fix it, change onPause in GpsTestActivity.java to add a check for orientation change:

        // Check if the user has chosen to stop GNSS whenever app is in background
        if (**!this.isChangingConfigurations() &&** Application.getPrefs().getBoolean(getString(R.string.pref_key_stop_gnss_in_background), false)) {
            gpsStop();
        }

**Comment by barbeau** [comment]
@rick-gse Thanks!  I'll take a look.

**Comment by barbeau** [comment]
@rick-gse Thanks for the proposed code!  I looked at a few possible solutions and given the complicated history of how GPSTest currently "works" in the background this is the simplest solution.  Ultimately background execution will be properly fixed in https://github.com/barbeau/gpstest/issues/299.

**Comment by gse-rick** [comment]
Glad to help. I also looked at also not stopping the listeners, but was worried about unintended consequences.
