### ISSUE TITLE
Status view - On narrow screens rows spill over

### ISSUE THREAD

**Issue by barbeau** [barbeau/gpstest#317]
**Summary:** 

On very narrow devices such as the Lenovo Z6 Youth (Lenovo Z6 lite?), on the Status screen the rows barely spill over.

From https://groups.google.com/d/msg/gpstest_android/vJU8UU5aMp8/9AhQe1jLBwAJ:

![image](https://user-images.githubusercontent.com/928045/62232923-65260400-b395-11e9-92bf-8eb44a801eb4.png)

**Steps to reproduce:** 

Open app to Status screen on narrow screen device such as Lenovo Z6 Youth

**Expected behavior:** 

All info for one satellite should appear on one row

**Observed behavior:** 

The degrees symbol barely spills over to the next line.

**Device and Android version:** 

Lenovo Z6 Youth

**Comment by barbeau** [comment]
Well, this might be a font issue again - I created an emulator with 6.30-inch display with a resolution of 1080x2340 pixels (from https://gadgets.ndtv.com/lenovo-z6-youth-edition-price-in-india-13079) and it looks like this:

![image](https://user-images.githubusercontent.com/928045/62236291-cb625500-b39c-11e9-8b7c-37b9b3f15e1d.png)

**Comment by barbeau** [comment]
So I can come close to reproducing this with a 1018 x 2340 xxhdpi setting, although the emulator only fills the columns with "30.0" values, and I need 3 digits like "130" to push the character to the next line.

I'm going to fix this by clipping out the ".0" for azimuth and elevation, which also addresses a previous request for this feature.

**Comment by goldfndr** [comment]
Thanks. For the record, that was #130 (my comments). Not ideal (I also am prone to bugging the other direction; see https://github.com/wiglenet/wigle-wifi-wardriving issue 27) but certainly good enough for every screenshot I've seen.

**Comment by barbeau** [comment]
Just to clarify what the implementation actually does - the number is rounded to a single digit the same as before, but then the text is altered so if it ends with `.0` that part is removed.

So the value `13.0` will appear as:
* `13`

...but the value `13.1` will still appear as:
* `13.1`
