### ISSUE TITLE
Translation and release cycle don't match

### ISSUE THREAD

**Issue by Meteor0id** [barbeau/gpstest#321]
I just noticed a new version was released. The changelog has only just been offered for translation, but the release has already been made. This results in the old translation of the changelog being used for the new version. The changelog therefore doesn't match with the release.

Proper release cycle would be:
1. make changes to the code
2. Push updated strings to transifex
3. Possibly release a beta
4. Wait one week to offer translators time
5. Pull translations and merge to master
6. stable release to play store

Yes, that means a delay, but that is a fact of life. Any incomplete translations will simply default to English, so that will not be a problem.

Also, even if no changes are made to the sourcecode, translations bight have changed over two or three weeks, and a new release should be made to the play store every two or three weeks with the new translations merged in so errors in translation will get corrected even between new releases.

**Comment by barbeau** [comment]
Yes, sorry about the rapid release cycle on this last one!

Typically I'll put out a beta (sign up [here](https://play.google.com/apps/testing/com.android.gpstest) if you're not already) and announce it on the [Google Group](https://groups.google.com/forum/#!forum/gpstest_android) and wait at least a week.  Then I'll release updates to translations to beta as well, and finally do a production release.

https://github.com/barbeau/gpstest/issues/287 through a monkey wrench into this process, as I had to cut multiple releases simultaneous (v3.4.0 and v3.2.11) across Google Play and F-Droid. I skipped the beta stage to rip the bandaid off and avoid any further issues.

So, for the next release I plan to get back to the normal cycle!
