### ISSUE TITLE
Enable/Disable switch color is similar to the Action Bar background

### ISSUE THREAD

**Issue by Meteor0id** [barbeau/gpstest#325]
Should be a different color, as it is very hard to discover the switch this way

Sorry for opening issue tickets about little things like these, I don't have time to write a PR right away and by opeing an issue we can atleast keep track of the issue. I might write the PR later.

**Comment by barbeau** [comment]
IIRC it's linked to the theme coloring, and I had to make a compromise between this and other UI components.  PRs are welcome for improvement, although you'll need to review the whole app when changes are made to make sure it's not making something else harder to see.

Could you add a screenshot so others know what you're talking about?

**Comment by Meteor0id** [comment]
![signal-attachment-2019-08-08-002103](https://user-images.githubusercontent.com/34976212/62661921-bbd1a600-b972-11e9-9549-26db29a7e529.png)

**Comment by Meteor0id** [comment]
![signal-attachment-2019-08-08-002103](https://user-images.githubusercontent.com/34976212/62662410-4535a800-b974-11e9-8518-93ac7f33ad34.png)
