### ISSUE TITLE
Split up Help text and acknowledgements in multiple small strings

### ISSUE THREAD

**Issue by Meteor0id** [barbeau/gpstest#329]
Every time a new translator is credited, the whole string including the entire faq is reset. Altjough we can retreive the previous translation, as translators we have to review tge entire string to make sure nothing else has changed.

Splitting it into small strings is the solution.

Two additional more complex changes:
- only show the aknoledhement string for the same language as the app is currently set to.
- to all languages exept English, add to some of tge expanations "(in English this named CF for Carrier Frequency)". Doing this gives the app an additoalal educational value because it shows that where English literature speaks of CF, in relates to this abbriviation in your own language.

I can write a PR for all of this, but I think it also requires someone who is a project manager on the transifex project to sort this out.

**Comment by barbeau** [comment]
@Meteor0id Good idea!  I like splitting out the contributors from the rest of the Help text.

Let's keep all contributors for all languages, though.

For the 2nd bullet point, I think this is just a change the translators would need to make, right?  Doesn't require code changes?

As far as Transifex goes, any changes to the app strings in GitHub should automatically be reflected in Transifex, so it should require any admin changes there.  It would require translators to copy/paste the relevant text from the old strings to the new ones.

I'd suggest we target this issue at splitting out the acknowledgements into a separate string, and let's continue the discussion of the other items at https://github.com/barbeau/gpstest/issues/323, as they are closely related. I don't want to sink a lot of effort into partially reformatting the text if we're going to completely overhaul the presentation.
