### ISSUE TITLE
Add compass degrees to Sky view

### ISSUE THREAD

**Issue by barbeau** [barbeau/gpstest#331]
**Summary:** 

Request from user:

>The only flaw is that it lacks the indication of degrees in the compass, like other similar app. 

**Steps to reproduce:** 

Look at Sky view

**Expected behavior:** 

Draw numbers on the compass (exact amount and design TBD) for the headings

**Observed behavior:** 

Only a north arrow is shown

**Device and Android version:** 

N/A

**Comment by paulle** [comment]
![compassrose svg](https://user-images.githubusercontent.com/4852079/75291107-dd688100-5821-11ea-87dd-b5bdbb41e36b.png)

**Comment by paulle** [comment]
I did this as a svg. Could it be a possible replacement for the current windrose in skyview?

**Comment by paulle** [comment]
x-special/nautilus-clipboard
copy
file:///home/chris/Downloads/compassrose.svg

**Comment by barbeau** [comment]
@paulle Thanks for putting that together! Possibly - I need to revisit this code. Currently it's just drawing on a raw Canvas, and I'm not sure off the top of my head how easy it would be to layer a vector graphic on top.

Could you put the SVG XML in a GitHub Gist? Or share a link to it via Google Drive or something similar?

**Comment by paulle** [comment]
https://drive.google.com/file/d/17YLEzUqp9zn5z7XV-b3BVN_xQPHmPqOK/view?usp=drivesdk

**Comment by paulle** [comment]
I had some problems with my google drive. For this reason I sent you an e-mail wit the files attached.
barbeaudev@gmail.com

**Comment by paulle** [comment]
![compassrose-5-degree-steps](https://user-images.githubusercontent.com/4852079/75505753-688d7680-59dc-11ea-81e0-f5428ed0c1ba.png)

**Comment by cjc7373** [comment]
This feature is nice to have. At least show N, E, W, S letters instead of just an arrow..
