### ISSUE TITLE
Xiaomi Mi 9 - Incorrect, unlabeled GNSS frequencies

### ISSUE THREAD

**Issue by TaaviE** [barbeau/gpstest#336]
**Summary:** 

A few GNSS frequencies don't have a nice name.

**Steps to reproduce:** 

Open GPSTest on a Mi 9

**Expected behavior:** 

What did you expect the app to do?

**Observed behavior:** 

The nice names aren't displayed for these frequencies:
* GALILEO 1602.000 MHz , ID 7, 19
* GALILEO 1561.098 MHz, ID 7, 19, 26, 31, 31
* BEIDOU 1602.000 MHz, ID 2, 5, 9, 13, 16
* Galileo SBAS 1602.000 MHz, ID 126, 136

**Device and Android version:** 

Mi 9, 9

**Comment by barbeau** [comment]
@TaaviE Thanks for reporting this!  Could you include a screenshot too?

Unfortunately it looks like these are bugs - as far as I can tell there aren't any real signals being broadcast at these frequencies. Here's an example GNSS frequency chart:

![image](https://user-images.githubusercontent.com/928045/63358933-b421e200-c320-11e9-846f-3d2f902b950f.png)

Could you please report this bug to Xiaomi and see what they say?

**Comment by TaaviE** [comment]
I can try asking Xiaomi to fix these.

![Screenshot_2019-08-20-14-01-07-870_com android gpstest](https://user-images.githubusercontent.com/15741449/63361338-9bddb180-c378-11e9-9327-1ebf0c424a3b.png)

**Comment by PedroVenancio** [comment]
Hi @barbeau and @TaaviE 

I also see several strange things in my Xiaomi Mi9, with Android 9 PKQ1.181121.001 and MIUI Global 10.2.13 (GPSTest v3.4.0 and v3.4.2).

![Screenshot_2019-08-16-00-16-02-315_com android gpstest](https://user-images.githubusercontent.com/1331581/63424149-b873fb00-c405-11e9-96ec-bd3f55a9c68b.jpg)

![Screenshot_2019-08-21-00-04-21-903_com android gpstest](https://user-images.githubusercontent.com/1331581/63424157-bd38af00-c405-11e9-9a52-cf844985139f.jpg)

1) Several GPS satellites repeated: ID 24 and ID 30 on L1;

2) GLONASS L5 label (is this supported?);

3) Galileu frequencies of 1561.098 MHz; 

4) BeiDou frequencies of 1602.000 MHz;

5) Galileu SBAS ID 136, with frequencies of 1561.098 MHz.

By the way, is SBAS supported by Mi 9? 

I must say that Mi 9 is a very disappointing device to me in terms of GNSS. It is a huge drawback when compared to Mi 8... The unsupported accumulated delta range data is the worst thing...

@TaaviE  What channels do you use to communicate with Xiaomi?

Thanks!

**Comment by TaaviE** [comment]
> Several GPS satellites repeated: ID 24 and ID 30 on L1;

I think some satellites do send two signals on two bands?

> Galileu frequencies of 1561.098 MHz;
> BeiDou frequencies of 1602.000 MHz;

I think these are in wrong order because the code that deals with the second GNSS bands has basically a small typo.

> By the way, is SBAS supported by Mi 9?

The support should exist on all Snapdragon 855 devices.

> I must say that Mi 9 is a very disappointing device to me in terms of GNSS.

The small typo that is in a library somewhere isn't that big of a problem honestly. I can get a GPS fix inside quite a few buildings and the accuracy outside is 2.5m easily 99.99% of the time when I've recorded long trips.

> The unsupported accumulated delta range data is the worst thing...

I'm curious, what can you do with that data?

> What channels do you use to communicate with Xiaomi?

The built-in "Feedback" application in settings. If enough people report a problem then they fix it.

**Comment by PedroVenancio** [comment]
Thanks for your feedback @TaaviE !

> 
> > The unsupported accumulated delta range data is the worst thing...
> 
> I'm curious, what can you do with that data? Also have you tried the MIUI beta maybe it exists there?
> 

Accumulated Delta Range is necessary for post-processing. Please, see this issue https://github.com/barbeau/gpstest/issues/268

**Comment by TaaviE** [comment]
> Accumulated Delta Range is necessary for post-processing. 

I found that information but I haven't found what (error) it corrects?

**Comment by PedroVenancio** [comment]
> 
> > Accumulated Delta Range is necessary for post-processing.
> 
> I found that information but I haven't found what (error) it corrects?

https://developer.android.com/reference/android/location/GnssMeasurement.html#getAccumulatedDeltaRangeMeters() 

https://insidegnss.com/generating-carrier-phase-measurements/

**Comment by benzfish** [comment]
Mi9 shows both L1 and L5 at the column L1, its a bug. 
Xiaomi will fix this bug in the next release.

**Comment by mimichris** [comment]
Hello,
On the latest version MI9, MIUI 10.2.14 of this month, no change, I wonder if they will really change something ....

**Comment by TaaviE** [comment]
They fixed some but not GALILEO, I submitted an error report, please do the
same and ask others as well.

**Comment by Bolognesus** [comment]
![Screenshot_2019-10-26-03-56-23-738_com android gpstest](https://user-images.githubusercontent.com/57024020/67612809-60ab9480-f7a6-11e9-9e2b-64feba82baaf.png)
Mi 9T pro, same issue.

**Comment by DominicHayes** [comment]
![Screenshot_2019-10-27-11-36-52-932_com android gpstest](https://user-images.githubusercontent.com/57133320/67755248-7dfb8f80-fa40-11e9-9da4-8d12b0649be0.png)
Impressed by the performance even at 10000m and 800kph, but the labels still need attention. 9T Pro.

**Comment by barbeau** [comment]
@DominicHayes Thanks for the screenshot! The carrier frequency of 1602 MHz for Galileo and Beidou is an error by Xiaomi - there are no real GNSS signals broadcast on these frequencies from these systems. Could you please report this bug to Xiaomi and see what they say? 

Has anyone else gotten a response from Xiaomi on this recently?

**Comment by TaaviE** [comment]
@DominicHayes 
![IMG_20191029_154505](https://user-images.githubusercontent.com/15741449/67772836-70a3cc80-fa63-11e9-8732-b92597a364b8.jpg)

I got 52 sattelites on almost the same altitude with a Mi 9, also has a few weird Galileo frequencies.

I'm waiting for MIUI11 to see if Xiaomi has fixed it there.

**Comment by PedroVenancio** [comment]
I've just updated to MIUI 11 and it seems that this issue was fixes:

![Screenshot_2019-11-04-23-55-16-320_com android gpstest](https://user-images.githubusercontent.com/1331581/68167896-10c78d00-ff5f-11e9-98b7-65513c7cba42.png)

**Comment by TaaviE** [comment]
Did the same, seems fixed indeed.

**Comment by mimichris** [comment]
Hello,
I do not have the possibility of this update yet, when did you have it?
Thank you.

**Comment by PedroVenancio** [comment]
> 
> 
> Hello,
> I do not have the possibility of this update yet, when did you have it?
> Thank you.

@mimichris  It landed in my Mi9 last night.

**Comment by mimichris** [comment]
Hello,Maybe I had not looked at the possibility of updating, I just made this update and I no longer have the satellite data error.
mimichris

**Comment by alpter** [comment]
Did you see this ? 
[https://insidegnss.com/galileo-hits-the-spot]()
