### ISSUE TITLE
Add number of signals ("# Signals:")

### ISSUE THREAD

**Issue by Vascom** [barbeau/gpstest#343]
**Summary:** 

"# Sats:" field show wrong number of satellites on L1/L5 receivers.

**Steps to reproduce:** 

Run app on L1/L5 receiver like Xiaomi Mi 9.

**Expected behavior:** 

Show real number of satellites even if one satellite has two signals.

**Observed behavior:** 

I see each signals as separate satellite.

**Device and Android version:** 

Xiaomi mi 9. MIUI 10.2.8.

**Comment by barbeau** [comment]
I've started working on logic that can support this at https://github.com/barbeau/gpstest/pull/355.

**Comment by Vascom** [comment]
Thanks.

Also it will be good if instead list second signal as new string you just show SNR of second signal in second column.

Like this:
Id    GNSS CF1cn0 CF2cn0 flags Elev Azim

**Comment by barbeau** [comment]
I just merged https://github.com/barbeau/gpstest/pull/355, so the "# Sats" value will now be correct on dual-frequency devices. I'll leave this open for showing "# Signals" as well in the UI (somewhere).

**Comment by barbeau** [comment]
Number of satellites should now be correct for dual-frequency devices in the new beta release v3.5.3 - https://play.google.com/apps/testing/com.android.gpstest.

If you have a dual-frequency device please test and let me know if it looks right!

**Comment by Vascom** [comment]
I tested on Xiaomi Mi 9.
Work good. Sats number as expected.

**Comment by barbeau** [comment]
Thanks @Vascom!
