### ISSUE TITLE
Improve "Install Barcode Scanner" dialog

### ISSUE THREAD

**Issue by Giolly90** [barbeau/gpstest#352]
**Summary:** 
When entering transifex I don't see the string showed in the screenshot

**Steps to reproduce:** 
Enter Accuracy view, tap on QR code icon, tap OK

**Expected behavior:** 
I see a message in my language

**Observed behavior:** 
I see a message in english

**Device and Android version:** 
OnePlus 5, Android 9

**Screenshots:** 
![Screenshot_20191016-101414](https://user-images.githubusercontent.com/46520205/66902864-b7280e80-f001-11e9-9a42-3e08bb39dd87.jpg)

**Comment by Giolly90** [comment]
Moreover, choice buttons YES/NO are not well defined

**Comment by barbeau** [comment]
@Giolly90 thanks for flagging this! Right now this screen is controlled by the Bar Code Scanner app library, so I don't have direct control over localizing it or fixing the buttons. I'll leave this issue open for improving this in the future and possibly replacing it with code in GPSTest.

**Comment by goldfndr** [comment]
[Relevant code](https://github.com/zxing/zxing/blob/master/android-integration/src/main/java/com/google/zxing/integration/android/IntentIntegrator.java#L115-L117)

**Comment by paulle** [comment]
Why not making the yes/no-buttons round, so they will be better separated.

**Comment by barbeau** [comment]
The yes and no buttons should follow the same normal material design dialog layout as the other dialogs in the app.

**Comment by paulle** [comment]
I understand, so the buttons should only be a little bit more separated.

Am 20. Oktober 2019 15:04:34 MESZ schrieb Sean Barbeau <notifications@github.com>:
>The yes and no buttons should follow the same normal material design
>dialog layout as the other dialogs in the app. 
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/barbeau/gpstest/issues/352#issuecomment-544250422

-- 
K-9 Mail
