### ISSUE TITLE
Provide version without maps and/or alternate map API provider

### ISSUE THREAD

**Issue by barbeau** [barbeau/gpstest#36]
I've received several requests to offer a maps-free version of the app, both so it could be included in an open-source market such as F-Droid (see discussion on adding GPSTest to F-Droid [here](https://f-droid.org/forums/topic/gps-test/)), as well as removing the requirement to download and install Google Play Services (which some users dislike with a passion).

We should be able to do this via build flavors in Gradle, and still support both versions (maps and no-maps) going forward.

One question is if we distribute the no-maps version via Google Play, or just offer the APK for sideloading off the website or downloading via F-Droid.

**Comment by barbeau** [comment]
Google Maps is no longer required for the app to install and run, so this is a lesser priority now.  Per my discussion with other app devs (e.g., stardroid), apparently F-Droid has relaxed their submission policy to allow for apps that do include proprietary dependencies.  So, I'll leave this issue open and we can attempt to resubmit this app to F-Droid again.

**Comment by AMDG2** [comment]
I am working on a GPS HAL. As my board is running AOSP I don't have Google Services installed. I would like to be able to display a map from OpenStreetMap instead of Google Maps.

Do you consider adding more providers for the map ?

**Comment by barbeau** [comment]
@AMDG2 I'm definitely open to adding more map providers, but the main blocking obstacle is that there aren't any other Map APIs/SDKs that have API parity with Google Maps API v2.  OSMDroid is the most popular, but it's API mirrors Google Maps API v1, not v2.  And it would take some effort to implement a Maps v1 version alongside v2.  I have a request into Mapzen for Google Maps API v2 API parity in their project here:
https://github.com/mapzen/android/issues/225

...but so far no traction.  If you happen to run into a Maps API/SDK that mirrors Google Maps API v2, definitely let me know.

**Comment by barbeau** [comment]
WIP PR at https://github.com/barbeau/gpstest/pull/149 for different build flavors - `google` for Google Maps, and `fdroid` for OSM Droid.
