### ISSUE TITLE
Number of sats used/in view not correct with dual frequency GNSS

### ISSUE THREAD

**Issue by schwabe** [barbeau/gpstest#361]
So this might be as well a wontfix. Before dual frequency number of satellites with lock was the same as number of frequencies with lock. With dual frequency that is no longer true.

I am not sure how to really improve on that. Maybe add a whole new section of stats? Like # sats with dual frequency, rename # Sats just to # Locks?

**Comment by barbeau** [comment]
@schwabe Thanks for pointing this out! Yes, I'm tracking this issue in https://github.com/barbeau/gpstest/issues/343, so I'm going to close this one as a duplicate.

To fix this field I need to implement grouping of satellites according to constellation, ID, and carrier frequencies, and this is almost done in https://github.com/barbeau/gpstest/pull/355.

**Comment by barbeau** [comment]
I'm actually going to re-open this issue and use it to specifically track fixing the "# Sats" label on dual-frequency devices. Showing both # Sats and #Signals requires a little more UI work so I'll continue tracking that in https://github.com/barbeau/gpstest/issues/343.

**Comment by barbeau** [comment]
Number of satellites should now be correct for dual-frequency devices in the new beta release v3.5.3 - https://play.google.com/apps/testing/com.android.gpstest.

If you have a dual-frequency device please test and let me know if it looks right!
