### ISSUE TITLE
Android 10 - Use force_psds_injection instead of force_xtra_injection

### ISSUE THREAD

**Issue by aleasto** [barbeau/gpstest#387]
`force_xtra_injection` got renamed to `force_psds_injection` in Android 10:
https://android.googlesource.com/platform/frameworks/base.git/+/master/services/core/java/com/android/server/location/GnssLocationProvider.java#1207

**Comment by barbeau** [comment]
Thanks for the heads up @aleasto! I'll work on adapting the app for this.

**Comment by barbeau** [comment]
Confirmed that this is new in Android 10 - the last tag of Android 9 still uses `force_xtra_injection`:
https://android.googlesource.com/platform/frameworks/base.git/+/refs/tags/android-9.0.0_r54/services/core/java/com/android/server/location/GnssLocationProvider.java#1451

**Comment by barbeau** [comment]
And here's the commit that changed it:
https://android.googlesource.com/platform/frameworks/base.git/+/8c6ac67a9657777b7f1d14f13cd2747f247185da

PSDS = Predicted Satellite Data Service

**Comment by barbeau** [comment]
Released in v3.6.3, currently out in beta on Google Play, if anyone with an Android 10 device that supports PSDS wants to test:
https://groups.google.com/forum/#!topic/gpstest_android/LulZpdhpHpM
