### ISSUE TITLE
Remove link to android.com from top of project page

### ISSUE THREAD

**Issue by jidanni** [barbeau/gpstest#392]
On https://github.com/barbeau/gpstest at the top we see:
> The `#1` open-source Android GNSS/GPS test program http://www.android.com

OK, but I would remove the http://www.android.com .

All the other Android apps here on GitHub don't have a link to  http://www.android.com at the top of their project page.

And you already have links to the app on Google Play etc. below.

**Comment by barbeau** [comment]
But tradition 😄! That's been there since Android 1.5, when this app was the first reference implementation for GPS on Android devices, when no one knew what Android was. But alas, you're right, it's time to remove it. It's now gone.
