### ISSUE TITLE
 Allow zooming  the Sky chart

### ISSUE THREAD

**Issue by jidanni** [barbeau/gpstest#398]
It's true that some items very close to each other on the sky chart will overwrite each other, even in landscape mode. Well, perhaps let the person zoom  the sky chart by moving his fingers apart.

**Comment by barbeau** [comment]
Some examples showing scaling on an Android canvas are here:
https://developer.android.com/training/gestures/scale#scale

...which point to this demo class:
https://android.googlesource.com/platform/development/+/master/samples/training/InteractiveChart/src/com/example/android/interactivechart/InteractiveLineGraphView.java

**Comment by jidanni** [comment]
Well besides automatically closing bugs, I suppose we can submit fewer ones too.

**Comment by jidanni** [comment]
Well besides automatically closing bugs, I suppose we can submit fewer ones too.
