### ISSUE TITLE
Be consistent with the sort icon on the status page

### ISSUE THREAD

**Issue by jidanni** [barbeau/gpstest#401]
When we first start the app, there is a sort icon at top, there on the status page.
Within a second or two, it becomes hidden and one has to tap the three dot menu to access sort.

You might as well be consistent and just put it in the menu from the start.

**Comment by jidanni** [comment]
I am speaking about portrait mode. In landscape mode it has a whole different story.

**Comment by barbeau** [comment]
@jidanni Thanks for the feedback! As you saw the menu items that appear in the overflow menu depend on the screen size, so I'd prefer to allow the Android platform to manage this.
