### ISSUE TITLE
Logging resets on a portrait/landscape mode change

### ISSUE THREAD

**Issue by Fuzl** [barbeau/gpstest#404]
**Summary:** 

A new log file is created on each portrait/landscape mode change

**Steps to reproduce:** 

- Launch app with file logging enabled. Go into "Accuracy" view. 
- Change from portrait to landscape
- An information bubble states a new logging file is created

**Expected behavior:** 

No new logging file on portrait/lanscape change

**Observed behavior:** 

**Device and Android version:** 

Pixel 4 device with latest 5th mai security update on an Android 10.
There is no Google Play Services app in my app lists :(  I guess they renamed it but could not find to what. So I cannot show the version.

**Screenshots:** 

![Screenshot_20200507-090612](https://user-images.githubusercontent.com/11424837/81265489-79451300-9043-11ea-82da-a992911f98c8.png)

**Comment by barbeau** [comment]
@Fuzl Thanks for reporting this! I'll take a look.

**Comment by barbeau** [comment]
Work-in-progress PR at https://github.com/barbeau/gpstest/pull/405.

**Comment by barbeau** [comment]
Looking at the master branch and latest release v3.8.4, logs are overwritten on a Samsung Galaxy S8+ w/ Android 9 instead of being appended to. Re-opening...
