### ISSUE TITLE
SBAS 125 does not have a flag

### ISSUE THREAD

**Issue by Giolly90** [barbeau/gpstest#407]
I spotted on a Samsung Galaxy A6+ this SBAS satellite number 125. What is it?
![IMG_20200520_175615](https://user-images.githubusercontent.com/46520205/82579971-d508b380-9b8e-11ea-9b90-3a182843445e.jpg)

**Comment by barbeau** [comment]
@Giolly90 Interesting, thanks for sharing! Looks like this is SDCM, which is Russia's SBAS system:
http://mgex.igs.org/IGS_MGEX_Status_SBAS.php

See also:
https://www.gpsworld.com/gnss-systemaugmentation-assistancenewsrussian-sbas-satellite-move-13114/

I'll work on adding this to the app so it shows the proper flag.

**Comment by Giolly90** [comment]
Thank you for the commitment to this fantastic app!
To add more details, I saw this sbas in northern Italy yesterday for a couple of minutes and then it was gone
