### ISSUE TITLE
Update FAQ: Replace XTRA with PSDS

### ISSUE THREAD

**Issue by curiousrom** [barbeau/gpstest#411]
In GPSTest v3.6.4 in the Menu & Help it says "Inject PSDS data" but in the github FAQ page at the present it says "Inject XTRA Data" & no mention at all of PSDS in the page: https://github.com/barbeau/gpstest/blob/master/FAQ.md

I do see in the [GPSTest](https://play.google.com/store/apps/details?id=com.android.gpstest&hl=en) Google Play page > WHAT'S NEW: "XTRA renamed to PSDS (Predicted Satellite Data Service)" but in the app's description it says > Menu options: Inject XTRA Data.

Also one of the screenshot was not updated & shows "Inject XTRA Data"

I was a bit thrown off when using the app for the first time by seeing "Inject PSDS" & not XTRA.

BTW nice & useful app, thank you!

**Comment by barbeau** [comment]
Thanks @curiousrom for flagging this! I just updated the FAQ and the Google Play listing. I'll work on replacing the screenshot on Google Play too.
