### ISSUE TITLE
breaking 'help_text' key into multiple strings on transifex

### ISSUE THREAD

**Issue by iriman** [barbeau/gpstest#415]
'help_text' in 'strings-xml' on transifex contains a long text. First translation is not a problem but:
- updating it is too hard because there is no diff tool available in transifex for source strings
- being that long, causes whole help content become untranslated by a small change in that string.

**Describe the solution you'd like**
Breaking this string into smaller parts could help.

Thanks

**Comment by barbeau** [comment]
Thanks @iriman, I agree this could help! There is already an issue open on this at https://github.com/barbeau/gpstest/issues/329 - let's continue the discussion there.
