### ISSUE TITLE
GPS not working

### ISSUE THREAD

**Issue by sandoxy** [barbeau/gpstest#423]
![Screenshot_2020-07-29_10-09-45](https://user-images.githubusercontent.com/38521726/88775905-95a9a500-d185-11ea-805d-64c22945a47d.png)
Recently my gps stopped working. No app is getting a gps signal, the search process never stops. I tried it at dufferent locations. But GPS Test seems getting a signal. How can I see, whether my gps sensor is not broken?

**Comment by barbeau** [comment]
@sandoxy Looks like there aren't enough satellites with a strong enough signal in view for your hardware to calculate a location fix - when you get a fix, a second bubble will be added with a thicker border, which shows the avg signal strength for satellites used in the fix.

I'd try rebooting your device outdoors with a clear view of the sky and a good wireless connection (cellular or Wi-Fi) - hopefully that will help.

I'm going to close this as it's not an issue with the app, but feel free to let me know if that works or you find another solution. Device details (make, model, Android version) would help too.
