### ISSUE TITLE
Can't edit Accuracy view longitude and latitude

### ISSUE THREAD

**Issue by gnusuari0** [barbeau/gpstest#424]
**Describe the bug**
Accuracy view 

**To Reproduce**
1. Go to accuracy view.
2. Tap on edit.
3. Tap on longitude or latitude textview.
4. Nothing happens.

**Expected behavior**
Software keyboard should appear, allowing to type coordinates.

**Observed behavior**
A clear and concise description of what actually happened.

**App, Device and Android version:** 
v3.7.2 (18069-osmdroid), OnePlus 7 Pro, Android 10, stock ROM Oxygen OS 10.0.6.GM21BA. Goole Services Framework version 10-5771379.

**Screenshots:** 

![228348d2-de29-416d-b2c2-488f39efd228](https://user-images.githubusercontent.com/36234118/89358671-48b55980-d6c4-11ea-9a56-127a2b3a07fc.jpg)

**Comment by gnusuari0** [comment]
And as you can see, OSM map does not load. The Map view works as expected.

**Comment by barbeau** [comment]
@gnusuari0 Thanks for reporting this! I noticed that something strange happened too - I updated the Android library used for the top card view it appears something broke in the process. I'll take a look.

**Comment by barbeau** [comment]
Looks like this was a bug in the `constraint-layout:2.0.0-beta6` library release.

Changing to `implementation 'androidx.constraintlayout:constraintlayout:2.0.0-rc1'` fixes this.

**Comment by barbeau** [comment]
This is fixed in the latest v3.7.3 release which is now in beta, if you want to test it out!

**Comment by gnusuari0** [comment]
Nice.I'm an F-Droid user... I'll wait for the app to be published there.
