### ISSUE TITLE
Log file has duplicate lines for "Fix" entries

### ISSUE THREAD

**Issue by YoavZangvil** [barbeau/gpstest#425]
**Describe the bug**
When enabling the logging "Location" option, the created log file has doubled entries for "Fix" entries

**To Reproduce**
1. Enable log
2. select Location
3. Run the app for a few minutes 
4. Close the app
5. Open the log file in a text viewer

**Expected behavior**
Each "Fix" line should be unique.

**Observed behavior**
There are double lines each time for each "Fix" entry

**App, Device and Android version:** 

App version 3.6.4
Devices observed: Huawei P20, Xiaomi Mi8, Samsung S8,S9,S10, Honor X10, Oppo Reno 10, Vivo X27
**Screenshots:**

**Comment by YoavZangvil** [comment]
Attached is a screenshot of the log file.

![Untitled](https://user-images.githubusercontent.com/66993685/89532441-78667d80-d7fa-11ea-9784-c019216b4dd9.png)

**Comment by barbeau** [comment]
Thanks for reporting this @YoavZangvil! The fix will be in the next beta release. If you're not signed up for beta updates and would like to check it out, see https://play.google.com/apps/testing/com.android.gpstest.

**Comment by barbeau** [comment]
This is fixed in the latest v3.7.3 release which is now in beta, if you want to test it out!
