### ISSUE TITLE
Adaptive icon support

### ISSUE THREAD

**Issue by staticssleever668** [barbeau/gpstest#430]
I want support for adaptive icons to be added as this is like an eyesore - in the app list where most of the icons are circle there are a few that doesn't fit the style. Most modern Android apps support it.

**Comment by barbeau** [comment]
@staticssleever668 Thanks for the reminder! That's something I can work on. Out of curiosity, could you share a screenshot of how this currently looks on your device, with you device make, model, and Android version?

**Comment by staticssleever668** [comment]
Sorry, but because of my stupid privacy reasons I can only give you these
![image](https://user-images.githubusercontent.com/64694940/91484193-67100e80-e898-11ea-9751-3f913071925d.jpg)
![image2](https://user-images.githubusercontent.com/64694940/91484202-6a0aff00-e898-11ea-99bc-3016d00cb187.jpg)

**Comment by JonnyTech** [comment]
@barbeau here is a selection from my Android 9 device
![img_6](https://user-images.githubusercontent.com/3584732/91490897-1655e100-e8ab-11ea-9074-cac3d5eda2d7.jpg)

**Comment by barbeau** [comment]
@JonnyTech @staticssleever668 Adaptive icon support is now in the beta release for v3.8.0 - could you please check it out and see if it looks better on your devices?

Sign up for betas from Google Play at:
https://play.google.com/apps/testing/com.android.gpstest

**Comment by JonnyTech** [comment]
Thanks @barbeau, but sorry but I do not use Google Apps so cannot access the beta. Can you provide a prebuilt apk?

**Comment by barbeau** [comment]
@JonnyTech Sure, see https://github.com/barbeau/gpstest/releases/download/v3.8.0/osmdroidRelease-v3.8.0.apk

**Comment by Giolly90** [comment]
It's working fine for me!
![Screenshot_20200901-223549](https://user-images.githubusercontent.com/46520205/91903650-dd9b7a80-eca3-11ea-985c-304740dd56e0.jpg)
![Screenshot_20200901-223538](https://user-images.githubusercontent.com/46520205/91903652-de341100-eca3-11ea-9dd4-029fe8e177b7.jpg)
![Screenshot_20200901-223513](https://user-images.githubusercontent.com/46520205/91903653-decca780-eca3-11ea-9195-2265127d2a79.jpg)
![Screenshot_20200901-223238](https://user-images.githubusercontent.com/46520205/91903655-decca780-eca3-11ea-99e9-e230e857e39f.jpg)

**Comment by JonnyTech** [comment]
Perfect here too - great job, thanks Sean!

![img_1](https://user-images.githubusercontent.com/3584732/91911255-94015e80-eca8-11ea-860d-c1ce7cb08ec3.jpg)

**Comment by barbeau** [comment]
Thank for testing - glad it works! 😅
