### ISSUE TITLE
White outlines for satellites in use for dark theme

### ISSUE THREAD

**Issue by paulle** [barbeau/gpstest#437]
White outlines for satellites in use (in sky view)  for the dark theme. The dark theme has the same bold black outlines for satellites in use as the light theme. These outlines
changing to white would lead to better visibility which satellites  are in use in the dark theme.

**Comment by barbeau** [comment]
@paulle Thanks for the feedback! I agree, a lighter outline for satellites on Sky view when in dark mode would be better.
