### ISSUE TITLE
Put tallies next to each item in the legend on Sky tab

### ISSUE THREAD

**Issue by jidanni** [barbeau/gpstest#438]
In Sky tab, at Legend, how about putting a tally next to each item?
E.g. 15 Navstar, (which would mean 15 Navstars on the sky map above the Legend.)

Or 15/22 meaning 15 visible out of a total of 22.

**Comment by barbeau** [comment]
@jidanni Thanks for the feedback! I'm planning another "Device Info/Summary" screen that this would fit better on, which is being tracked at https://github.com/barbeau/gpstest/issues/313. I've updated that issue to have a reference to this one, so I'm going to close this issue.
