### ISSUE TITLE
Can google maps be replaced by other mapping software？

### ISSUE THREAD

**Issue by skittlz-lab** [barbeau/gpstest#455]

**Comment by barbeau** [comment]
Yes! Please check out the F-Droid release for non-Google Maps devices - https://f-droid.org/packages/com.android.gpstest.osmdroid/.

**Comment by skittlz-lab** [comment]
but this one also uses Google Maps..:(

**Comment by barbeau** [comment]
Nope, the F-Droid release uses [OSMDroid](https://github.com/osmdroid/osmdroid) with a combination of Mapbox and Maptiler tiles that are based on [OpenStreetMap](https://www.openstreetmap.org/) data.

**Comment by skittlz-lab** [comment]
Ok thanks for your answer :)

**Comment by skittlz-lab** [comment]
But the source code I downloaded and then imported into the phone from Android studio is wrong

**Comment by skittlz-lab** [comment]
than still uses Google Maps

**Comment by barbeau** [comment]
You'll want to build the osmdroid flavor - see https://github.com/barbeau/gpstest/blob/master/BUILD.MD#building-in-android-studio
