### ISSUE TITLE
Wrong layout in share dialog

### ISSUE THREAD

**Issue by sm4rk0** [barbeau/gpstest#457]
**Describe the bug**
Actions in the share dialog are drawn over the "Include altitude" checkbox.

**To Reproduce**
1. Open the app
2. Tap the share button

**App, Device and Android version:** 

GPSTest 3.9.1
Samsung Galaxy S10e
Android version 10 (stock)
Google Play Services 20.47.13

**Screenshots:** 

[Google photos](https://photos.app.goo.gl/qXQnB3kjnwRSMjMHA), before and after checking the "Include altitude" checkbox.

**Comment by naoliv** [comment]
Indeed:
![](https://user-images.githubusercontent.com/982338/102024369-6086a380-3d70-11eb-83a9-755bec760a96.png)

It's also not possible to properly see the send button at the last share screen:

![](https://user-images.githubusercontent.com/982338/102024391-857b1680-3d70-11eb-98b9-87a8beb95102.png)

**Comment by barbeau** [comment]
@sm4rk0 @naoliv Thanks for flagging this! Seems like the layout isn't working the same on all devices, then :(.

@naoliv Which device and Android version are your screenshots from?

**Comment by naoliv** [comment]
Mine is a Mi A2 Lite, with Android 10.

**Comment by sm4rk0** [comment]
If it helps, my font size setting is 3/8 and zoom is 1/5.

**Comment by naoliv** [comment]
@barbeau the last screen still isn't right here:

![](https://user-images.githubusercontent.com/982338/102693130-09ad1e00-41f7-11eb-8915-85ac2739c1e0.png)

If I select the text it gets resized to the proper size:

![](https://user-images.githubusercontent.com/982338/102693128-074ac400-41f7-11eb-95de-6fa29be4c082.png)

If I play with `Include altitute`:

![](https://user-images.githubusercontent.com/982338/102693124-0023b600-41f7-11eb-8435-cdae9812a3e6.png)

It's also properly resized:

![](https://user-images.githubusercontent.com/982338/102693126-044fd380-41f7-11eb-8308-98475fc0afef.png)

**Comment by barbeau** [comment]
@naoliv Thanks! Could you open a new issue for that please?
