### ISSUE TITLE
Screen rotation re-starts GPS synchronisation from the beginning

### ISSUE THREAD

**Issue by Totorrr** [barbeau/gpstest#466]
**Bug description**
While in the app main panel (showing satellites list), if the screen rotates (portrait or landscape), the GPS signals lookup re-starts from the beginning. 

**To Reproduce**
1. Go to the app main screen with location services enabled & allowed 
2. Wait for some satellites to lock '# Sats' would show '0/2/36' for example if 2 satellites signals are in sync
3. Rotate the screen (screen auto rotation must be enabled in Android parameters)
4. See that the satellites list clears for a few seconds, comes back, and '# Sats' has no synced signals anymore (shows '0/0/36'). 

**Expected behavior**
The screen rotates without changing the app GPS operation/behavior (it would just go to landscape or portrait mode, changing only the display)

**Observed behavior**
The satellites list clears for a few seconds, comes back, and '# Sats' has no synced signals anymore (shows '0/0/36'). After a few seconds, satellites signals come again. 

**How is it unwanted?**
This is especially annoying when getting a fix takes times, and some satellite signals were locked, and the screen rotates, those locked signals are not locked anymore, and the process "resets". This makes the process for getting a location 1st fix longer. 

**App, Device and Android version:** 
* Sony Xperia XZ1 compact on Android 9 with official manufacturer ROM
Google Play Services 20.45.16

* GPS Test app
v3.9.3 (18080-osmdroid)
GNSS HW Year: 2016
Platform: 9
API Level: 28

**Related bugs**
This bug seems close to the #310 bug.

**Comment by barbeau** [comment]
@Totorrr Thanks for the report! So unfortunately this is intended behavior due to the lifecycle of Android Activities until I can implement true background execution in https://github.com/barbeau/gpstest/issues/299. I agree it's not ideal, but it's what we have to work with for now...
