### ISSUE TITLE
Large font text overflows on Status screen

### ISSUE THREAD

**Issue by franklinbill** [barbeau/gpstest#467]
**Describe the bug**
Dear developer!
In the process of using, I found a bug in layout / display. As shown in the figure, in the first page, the text in the red box is half blocked. This may be an adaptation problem. I suspect it is because **display and font size** are set to large (mainly due to **display size**).
Because of some problems with my eyesight, I often use the largest font and display.
![297165ECE247F4EDC808C49B7E0633F7](https://user-images.githubusercontent.com/18572115/103165857-dbaf8580-4857-11eb-9e22-120ae1901389.png)
App version is 3.9.3, my mobile phone is Google nexus 6, screen resolution setting is 1920* 1080, **_font size and display size are the largest ! ! !_**, Android system is 8.0.
The above is a description of the problem. The overall experience of the software is good. You can see that the design is very attentive. Thank you very much for the efforts of the developers all the time. I hope to receive a reply.
<img width="469" alt="bug-osmdroid" src="https://user-images.githubusercontent.com/18572115/103220120-6bd5f380-495a-11eb-92b8-d5c91b1a2529.png">

**To Reproduce**
1. use the largest font and display
2. See error

**Expected behavior**
I suggest that you can set the width and height of the component to adaptive text

**Observed behavior**
A clear and concise description of what actually happened.
As shown in the figure, in the first page, the text in the red box is half blocked.

**App, Device and Android version:** 

App version is 3.9.3, my mobile phone is Google nexus 6, screen resolution setting is 1920* 1080, **_font size and display size are the largest ! ! !_**, Android system is 8.0. From F-droid

**Screenshots:** 
![bustorino_30](https://user-images.githubusercontent.com/18572115/103220268-d2f3a800-495a-11eb-82f0-6b0111bf00e9.png)

Can be created by pressing the Volume Down and Power Button at the same time on Android 4.0 and higher.

**Comment by barbeau** [comment]
Thanks @franklinbill for the feedback. I'm adding a horizontally scrolling section to these cards, so if they overflow text you should just be able to scroll over.
