### ISSUE TITLE
Device Database -- CSC/Carrier Customization

### ISSUE THREAD

**Issue by danieldjewell** [barbeau/gpstest#468]
I really like the device database! I think it provides some really interesting insight, and I do like that you've been mindful of what data to push (instead of just dumping everything), so kudos on that!

I wonder if maybe grabbing the CSC info (e.g. carrier customizations - at least on Samsungs, not sure about other brands) and/or the "Home" PLMN (e.g. the MCC/MNC of the SIM card) would provide additional insights? Without being too intrusive on privacy?

At least with the Samsung phones sold in the US (Qualcomm SoCs), the hardware itself is (theoretically) identical between carriers and it's only when you stick a differrent SIM in that it switches. For example, putting in an AT&T sim on a phone that was originally T-Mobile causes a bunch of changes (including the automatic removal of the T-Mobile apps and installation of AT&T apps). It's possible that the device behaves differently as I believe GPS/GNSS settings are one of the things that could be customized. (It goes further than that even - I was in NZ and with a T-Mobile similar couldn't use LTE Band 28 - same phone, Spark NZ SIM, and B28 magically appeared.....)

Also, looking at the home MCC/MNC + user location country could show of it's roaming (for those interesting cases that you reported on where the GNSS settings change based on where you are.)

**Comment by barbeau** [comment]
@danieldjewell Thanks, I'm glad you find it useful!

Yeah, this is a tough one. Do you know which exact Android APIs this info would be coming from? I certainly see the usefulness, but Google has been locking down Android so accessing certain API groups like the Telephony API has become harder without requiring more in-app permissions and raising red flags with Google. I'm going to have to walk a fine line between gathering potentially useful information and treading into privacy sensitive API territory (even if the final info that ends up in the database isn't privacy sensitive). I'll look into the APIs myself too.
