### ISSUE TITLE
Screenshots for F-Droid 

### ISSUE THREAD

**Issue by mondlicht-und-sterne** [barbeau/gpstest#470]
You can add Screenshots for F-Droid, too, if you want. https://f-droid.org/en/docs/All_About_Descriptions_Graphics_and_Screenshots/ https://gitlab.com/snippets/1895688 That was simply information about what is still possible. You would then only have to enter the screenshots in fastlane.

**Comment by barbeau** [comment]
Here's a recent example from SkyMap:
https://github.com/sky-map-team/stardroid/pull/418

**Comment by barbeau** [comment]
Relevant files for GPSTest:
* https://gitlab.com/fdroid/fdroiddata/-/blob/master/metadata/com.android.gpstest.osmdroid.yml
* https://gitlab.com/fdroid/fdroiddata/-/tree/master/metadata/com.android.gpstest.osmdroid

**Comment by barbeau** [comment]
Ok, I believe I've added the relevant info for Fastlane to this repo via https://github.com/barbeau/gpstest/commit/71412d06167b50c1fc107adcb2bb82ae457fd434. 

My understanding is that this info in the repo will override the info in the files linked in the above comment. I don't know how long it will take to sync.

If someone who knows more about this than me could check it out and see if it looks right that would be great :).

**Comment by barbeau** [comment]
Reopening, as the last release didn't seem to change anything - I'm not sure why:
https://f-droid.org/packages/com.android.gpstest.osmdroid/

**Comment by barbeau** [comment]
Oh, it looks like 3.9.15 hasn't been picked up by Fdroid yet - that's probably why.

**Comment by barbeau** [comment]
This is done, the screenshots appeared when 3.9.15 went live on FDroid:

![image](https://user-images.githubusercontent.com/928045/140440980-de726b04-485b-4909-beb9-e96651df15fc.png)
