### ISSUE TITLE
Add CarrierPhase (AccumulatedDeltaRange) SUPPORT in Email

### ISSUE THREAD

**Issue by webvan1999** [barbeau/gpstest#479]
Would it be possible to show ADR Support in the Email feedback form and not only the Database feedback where the user can't see what's being sent as far as I can tell ?

Maybe specify that ADR support matters because it's a requirement for post-processing via RTP or PPP, something like :

CarrierPhase Data (needed for RTK or PPP) : SUPPORTED

**Comment by barbeau** [comment]
This should be do'able. Also for items like automatic gain control.
