### ISSUE TITLE
Vertical accuracy is always 100,0 meters

### ISSUE THREAD

**Issue by inode64** [barbeau/gpstest#500]
**Describe the bug**
Since I bought this mobile phone  Samsung Galaxy Xcover Pro it has always shown the vertical accuracy as 100 meters independently of the altitude, visibility of the satellites or the time I wait, the same happened when I had  the version Android 10

**To Reproduce**
I enable GPS and open gpstest and wait some seconds to show this problem

**Expected behavior**
Show the actual vertical accuracy  

**Observed behavior**
It always shows 100 meters

**App, Device and Android version:** 
App version: v3.9.11 (18088-google)
Model: SM-G715FN
Android version: 11 / 30
Location: gps, hor acc 2.0m, 1 second(s) ago
GNSS HW year: 2016
GNSS HW name: S.LSI,K102
Raw measurements: SUPPORTED
Navigation messages: SUPPORTED
NMEA: SUPPORTED
Inject PSDS: SUPPORTED
Inject time: SUPPORTED
Got fix: true
Dual frequency: NOT_SUPPORTED
Supported GNSS: GPS, GLONASS, GALILEO, BEIDOU
GNSS CFs: B1, E1, L1
Accumulated delta range: SUPPORTED
Automatic gain control: SUPPORTED
GNSS antenna info: NOT_SUPPORTED

Google Play Services App: 21.12.13 (150400-367530751)
Google Play Services Library: 12451000

**Screenshots:** 
![WhatsApp Image 2021-04-14 at 21 10 21](https://user-images.githubusercontent.com/1045720/114772832-92376780-9d6e-11eb-8dbf-41b157479636.jpeg)

**Comment by barbeau** [comment]
@inode64 Thanks for opening this! Unfortunately this looks like Samsung is hard-coding that value to 100m, which isn't right. 

The Android API spec:
https://developer.android.com/reference/android/location/Location#getVerticalAccuracyMeters()

...says:

>We define vertical accuracy at 68% confidence. Specifically, as 1-side of the 2-sided range above and below the estimated altitude reported by getAltitude(), within which there is a 68% probability of finding the true altitude.
>
>In the case where the underlying distribution is assumed Gaussian normal, this would be considered 1 standard deviation.

Could you open an issue with them and let us know how it goes? Please link if it's public.

Unfortunately there isn't anything I can do in GPSTest to change this so I'm going to close the issue, but please feel free to comment with updates.
