### ISSUE TITLE
Log to dedicated folders

### ISSUE THREAD

**Issue by vkbellis** [barbeau/gpstest#506]
GPSTest and GnssLogger appear to want to share a common folder on my phone by default:
../storage/emulated/0/gnss_log/ 

This becomes even more confusing trying to discern which app created which file by their similarities in file naming schema, for example, here we see both apps' files with (2) from GPSTest:

![whose app is it](https://user-images.githubusercontent.com/82275968/115786461-d63df400-a38e-11eb-96eb-a8a30e50c240.PNG)

Consider having GPSTest by default create its own parent folder; e.g., ../storage/emulated/0/GPSTest_logs/ 
and then beneath it, sub-folders for each instance that GPSTest in run; e.g., 
../storage/emulated/0/GPSTest_logs/202104180600/
../storage/emulated/0/GPSTest_logs/202104180300/
../storage/emulated/0/GPSTest_logs/202104151530/

**Comment by barbeau** [comment]
Logging implementation will change as part of the transition to scoped storage as discussed in https://github.com/barbeau/gpstest/issues/447, so I'll keep this in mind for that issue.
