### ISSUE TITLE
Show intro dialog when opening logging preferences

### ISSUE THREAD

**Issue by vkbellis** [barbeau/gpstest#509]
**Separate Settings for Logging, Android Studio**
Under the heading Android Monitor Output, we see (4) boxes, and that when these boxes are all checked, it's unclear what, if anything, is going on.

![6 boxes 2 logs](https://user-images.githubusercontent.com/82275968/115790218-6af72080-a394-11eb-9cb4-71d505439a70.PNG)

Android Studio settings (keep under main menu, Settings) ought to be separate and apart from Logging Settings.

**Comment by barbeau** [comment]
I think a brief explanation in a dialog of what these settings are would be helpful here, along with a link to https://github.com/barbeau/gpstest/blob/master/LOGGING.md - they are both logging, the Android Studio option is just more relevant to developers. I'm going to change this issue to focus on that, which should mitigate the problem.
