### ISSUE TITLE
Change log file naming schema

### ISSUE THREAD

**Issue by vkbellis** [barbeau/gpstest#513]
The file naming schema presented in Issue #507 is largely predicated upon the naming convention shared with the app GnssLogger, wherein the prefix of 'gnss_log_' is common with all files created by GPSTest. This nomenclature schema may also be used in other smartphone apps, but it isn't the standard naming convention that's used in the broader GNSS industry. For most smartphone users that want to check the accuracy of their smartphone's location capabilities using logged data, this non-standard naming convention is adequate and does not require the user to do very much beyond toggling (#510) logging on/off, and so long as there are discrete folders (#506), and housekeeping issues will hopefully be minimal.

**STATION NAME**
GPSTest would be improved tremendously if the user was optionally able to provide the name of the occupied station, marker, or monument; e.g., SINCLAIR A, AL7621, XACT 2, DG8939. This is a basic standard naming convention and a good place to begin. 

**START TIME**
Following the station name and separated by an underscore_ the start time of the RINEX file YYYYDDDHHMM where DDD is the day of the year.

**CONTENT TYPE**
Following the start time and separated by an underscore_ the content type represented by 2 characters; i.e.,
Two uppercase characters represent the data type: 
GO - GPS Obs. 
RO - GLONASS Obs. 
EO - Galileo Obs. 
JO - QZSS Obs. 
CO - BDS Obs. 
IO – NavIC/IRNSS Obs. 
SO - SBAS Obs. 
MO - Mixed Obs. 
GN - Nav. GPS 
RN - GLONASS Nav. 
EN - Galileo Nav. 
JN - QZSS Nav. 
CN - BDS Nav. 
IN – NavIC/IRNSS Nav. 
SN - SBAS Nav. 
MN – Mixed Nav. (All GNSS Constellations) 
MM-Meteorological Observation 

**EXTENSION**
Following the content type and separated by the decimal . **rnx** for all RINEX files.

This is not by any means the full-on OCD RINEX file naming schema of IGS, as is more fully detailed in RINEX v. 3.05 and the [RINEX Formating standards](https://www.igs.org/wg/rinex/#documents-formats) leading up last December's major restructuring. There may be [softwares](http://acc.igs.org/software.html) available to help in generating RINEX 3.xx long filenames.

**Comment by barbeau** [comment]
I'm going to close this and group custom file naming under https://github.com/barbeau/gpstest/issues/511 for custom settings as well.
