### ISSUE TITLE
Bum link in gnss_log_ header

### ISSUE THREAD

**Issue by vkbellis** [barbeau/gpstest#521]
gnss_log_
Line 15

# NMEA format (for [NMEA sentence] format see https://www.gpsinformation.org/dale/nmea.htm):

URL never loads

**Comment by barbeau** [comment]
Thanks @vkbellis for spotting this!

**Comment by barbeau** [comment]
Fixed in https://github.com/barbeau/gpstest/commit/fa88623988ca3965d70fc3fceaead7958cbbc91e.

**Comment by vkbellis** [comment]
Thanks Sean!

FWIW - A little more satisfactory overview:
https://www.trimble.com/OEM_ReceiverHelp/V4.44/en/NMEA-0183messages_MessageOverview.html

**Comment by barbeau** [comment]
That's certainly a more informative link, although at this point my goal is finding one that's not as likely to break. Wikipedia seems like the best option (?).
