### ISSUE TITLE
lost lock identifier

### ISSUE THREAD

**Issue by Spring-L0101** [barbeau/gpstest#541]
I have a question: how do you get the lost lock identifier from the GnssMeasurement.getState() ?

**Comment by barbeau** [comment]
Good question - I don't 😁. Instead, for every update to the GnssStatus listener I check the difference between current time and the last fix time. If it's over a threshold then I consider the lock lost. Code here:
https://github.com/barbeau/gpstest/blob/7c599e14190d2bbc0e66b11a5d362bbeee83c6e2/GPSTest/src/main/java/com/android/gpstest/GpsTestActivity.java#L1137
