### ISSUE TITLE
Changelog info to F-Droid

### ISSUE THREAD

**Issue by aha999** [barbeau/gpstest#559]
**Is your feature request related to a problem?**

Currently, there is no visible window with the latest changes when you open your app's page in F-Droid.

**Describe the solution you'd like**

Add changelog text into a window above the description when you open the fdroid app repo.

**Some tips:**

> F-Droid looks for metadata in the app’s source repo. The supported formats for this metadata are borrowed from popular projects that automate uploading this metadata to Google Play Store.

>The one in your example corresponds to Fastlane Supply and is documented [here](https://docs.fastlane.tools/actions/supply/#changelogs-whats-new). All formats supported by F-Droid are listed [here](https://f-droid.org/en/docs/All_About_Descriptions_Graphics_and_Screenshots/#in-the-applications-source-repository)

**Additional context**

This would be a great option to quickly see the new changes and many apps use this method.

**Comment by barbeau** [comment]
@aha999 Thanks for the request! Yes, I'll add this. I believe F-Droid will pull it on the next release.

**Comment by barbeau** [comment]
Here's the directory structure:

```
└── fastlane
    └── metadata
        └── android
            ├── en-US
            │   └── changelogs
            │       ├── default.txt
            │       ├── 100000.txt
            │       └── 100100.txt
            └── fr-FR
                └── changelogs
                    ├── default.txt
                    └── 100100.txt
```

**Comment by aha999** [comment]
oh, right, totally forgot :laughing: thanks
