### ISSUE TITLE
Russian SBAS (SDCM) L1 label is missing

### ISSUE THREAD

**Issue by barbeau** [barbeau/gpstest#585]
**Describe the bug**
A user provided this screenshot, which shows that the Russian SDCM SBAS satellites aren't showing the L1 label correctly:

![image](https://user-images.githubusercontent.com/928045/162812727-a1cc5d4e-5fc2-4012-8bb3-8f3d669e9d7c.png)

I should also review to make sure that all other SBAS are fully implemented. Looking at `CarrierFreqUtils.getSbasCf()`, it looks like we have mappings for the following SBAS:
1. EGNOS (EU)
2. MSAS (Japan)
3. GAGAN (India)
4. WAAS (US)

**To Reproduce**
1. Be in view of Russian SBAS satellite

**Expected behavior**
Carrier frequency of `1575.42` should be shown as `L1`.

**Observed behavior**
Raw CF is shown instead

**App, Device and Android version:** 

App version: v3.9.16 (18093-google)
Model: SM-S908U1 (Samsung Galaxy S22 Ultra unlocked)
Android version: 12 / 31
GNSS HW year: 2020
GNSS HW name: qcom,SM_WAIPIO,MPSS.DE.1.0.c4-00029-WAIPIO_GEN_PACK-1.3475.171,

**Screenshots:** 

Can be created by pressing the Volume Down and Power Button at the same time on Android 4.0 and higher.

**Comment by barbeau** [comment]
Here are the SBAS we currently support (i.e., show a flag for instead of leaving it blank as unknown):

```kotlin
fun Int.toSbasType(): SbasType {
        if (this == 120 || this == 123 || this == 126 || this == 136) {
            return SbasType.EGNOS
        } else if (this == 125 || this == 140 || this == 141) {
            return SbasType.SDCM
        } else if (this == 130 || this == 143 || this == 144) {
            // Also referred to as BDSBAS
            return SbasType.SNAS
        } else if (this == 131 || this == 133 || this == 135 || this == 138) {
            return SbasType.WAAS
        } else if (this == 127 || this == 128 || this == 139) {
            return SbasType.GAGAN
        } else if (this == 129 || this == 137) {
            return SbasType.MSAS
        }
        return SbasType.UNKNOWN
    }
```

We should support all the same svids for CFs.

**Comment by barbeau** [comment]
For more info on SVIDs of SBAS see:
https://www.igs.org/mgex/constellations#sbas

**Comment by ValZapod** [comment]
Same on my galaxy s22 ultra 0 model:

![Screenshot_20220927-151623_GPSTest](https://user-images.githubusercontent.com/31514790/193412651-b9d76013-b944-41eb-b149-13ec4ce3980f.png)

**Comment by ValZapod** [comment]
See 
![Uploading Screenshot_20221026-052709_Adobe Acrobat.png…]()

**Comment by ValZapod** [comment]
Oh. I cought both, 140 is LUCH 5V.
![Screenshot_20221103-172700_GPSTest](https://user-images.githubusercontent.com/31514790/199757000-304fdc60-0d5e-4fd5-a22b-e6664d4e635d.png)

**Comment by ValZapod** [comment]
I also got the confirmation that this is indeed the frequency they operate on.

**Comment by barbeau** [comment]
Fixed by https://github.com/barbeau/gpstest/commit/08cb7b5cf8f01267399097fc0ff02829865d920f
