### ISSUE TITLE
prnBit exceeds a 32-bit bitmask for PRNs other than GPS?

### ISSUE THREAD

**Issue by mbavaro** [barbeau/gpstest#60]
In the current version of GpsStatusFragment.java at lines 387 and beyond, prnBit will exceed the size of a 32-bit bitmask for PRNs other than GPS. A similar approach as the one used for mPrns[], mSnrs[], etc.. could perhaps be used to overcome this small limitation?

**Comment by barbeau** [comment]
Ah, good catch - I guess this is because GPS PRNs were never intended to be 3 digits?

Yes, storing an array of booleans for each of these should be a pretty easy fix.
