### ISSUE TITLE
Take a picture and add GPS data to the exif metadata of the image option for app

### ISSUE THREAD

**Issue by PeterCullenBurbery** [barbeau/gpstest#600]
**Is your feature request related to a problem? Please describe.**
My phone does not add all the GPS data available to the metadata of a picture for later analysis. I'm able to extract some of the GPS metadata, but some data is missing even though the phone has access to it like GPS satellites in view and GPS speed.
**Describe the solution you'd like**
I would like to request a feature where you can take a picture with the app and it will add all the GPS data extracted with the application to the metadata of the picture stored in the EXIF metadata file. I would like to request the following GPS metadata elements:
"GPSAltitude", "GPSAltitudeRef", "GPSAreaInformation", \
"GPSDateStamp", "GPSDestBearing", "GPSDestBearingRef", \
"GPSDestDistance", "GPSDestDistanceRef", "GPSDestLatitude", \
"GPSDestLatitudeRef", "GPSDestLongitude", "GPSDestLongitudeRef", \
"GPSDifferential", "GPSDOP", "GPSImgDirection", "GPSImgDirectionRef", \
"GPSLatitude", "GPSLatitudeRef", "GPSLongitude", "GPSLongitudeRef", \
"GPSMapDatum", "GPSMeasureMode", "GPSPositioningError", \
"GPSProcessingMethod", "GPSSatellites", "GPSSpeed", "GPSSpeedRef", \
"GPSStatus", "GPSTag", "GPSTimeStamp", "GPSTrack", "GPSTrackRef", \
"GPSVersionID"

**Describe alternatives you've considered**

**Additional context**
There is an app iNaturalist that I think displays the gps precision when you take a picture of a plant.

**Comment by barbeau** [comment]
Here is a good API doc that lists all the Exif tags that are supported:
https://developer.android.com/reference/androidx/exifinterface/media/ExifInterface

**Comment by PeterCullenBurbery** [comment]
I looked at the webpage. I don't know how to program an Android app.

**Comment by barbeau** [comment]
@PeterCullenBurbery no worries 😁. It's mainly a note to whoever takes us on in the future.

**Comment by PeterCullenBurbery** [comment]
I have an example with a lot of GPS calculations at https://www.wolframcloud.com/obj/04327028-71ea-4d5b-a3d1-f4be1e522195

**Comment by PeterCullenBurbery** [comment]
I will note that not all of the gps document is related to gps files, some is related to Mathematica, but I have some helpful information present.
