### ISSUE TITLE
$GPGST NMEA sentance missing

### ISSUE THREAD

**Issue by wiltonp80** [barbeau/gpstest#602]
When logging NMEA messages, $GPGST messages are missing which record accuracy details. They exist in the raw log with both horizontal and vertical accuracy in version 3.9.16, just not in the NMEA log

Can these sentences be added please as this would make my analysis app even more dynamic as it already incorporated this for other, direct NMEA GNSS outputs.

**Comment by barbeau** [comment]
NMEA sentences are not required to be supported on Android, so it's really up to the device OEM as to what they output. Some OEMs output their own proprietary NMEA sentence types too. So unfortunately GPSTest doesn't have any control over this, so I'm closing this.
