### ISSUE TITLE
Add themed icon (Android 13)

### ISSUE THREAD

**Issue by vytskalt** [barbeau/gpstest#606]
**Is your feature request related to a problem? Please describe.**
This is one of the only apps I have that doesn't have support for the themed icons feature in Android 13.

**Describe the solution you'd like**
Add a themed icon
https://developer.android.com/about/versions/13/features#themed-app-icons

**Describe alternatives you've considered**
None

**Comment by botanegg** [comment]
https://github.com/barbeau/gpstest/blob/master/icons/inverse_satellite.svg could be used as base icon
