### ISSUE TITLE
Incorrectly display of BeiDou SBAS

### ISSUE THREAD

**Issue by MariaBombardier** [barbeau/gpstest#632]
**Summary**
The Chinese Government has already provided BeiDou SBAS service in China and surrounding countries&regions but in testing status.
However, it is now normally receive BeiDou SBAS signals in B1C (1575.420MHz) & B2a (1176.450MHz) Frequency bands.

**Describe the bug**
When I use GPSTest in China and surrounding countries&regions, the lable of BeiDou SBAS can't be identified correctly.

**To Reproduce**
1. Go to the Status Page
2. Wait the searching of SBAS satellites 

**Expected behavior**
It will display potentially discoverable SBAS satellites in Asia-Pacific like SNAS, GAGAN&MSAS.

**Observed behavior**
The satellites of CF code 1575.420 without country flag tag will be displayed.

**App, Device and Android version:** 

App version: 3.9.16 (18093-osmdroid)
Device: XiaoMi Mi 13
OS: MIUI 14.0.21 (Android 13 with kernel 5.15.41)
**Screenshots:** 
![Screenshot_2023-04-20-17-50-42-551_com android gpstest osmdroid](https://user-images.githubusercontent.com/31150880/233401844-6b279a2e-4d27-450f-b05d-f14c75ee3ec7.jpg)

**Comment by MariaBombardier** [comment]
Status of BeiDou System: http://www.csno-tarc.cn/en/system/constellation
Part of BeiDou SBAS satellites: 
![image](https://user-images.githubusercontent.com/31150880/233407040-6110958b-5d90-407f-a3de-9739437bc8ee.png)

**Comment by barbeau** [comment]
@MariaBombardier Thanks for reporting this! I'll fix it in the next release.

**Comment by barbeau** [comment]
https://www.igs.org/mgex/constellations#sbas shows that 130 is BDS as well.

**Comment by barbeau** [comment]
It looks like 134 is actually the new Korean Augmentation Satellite System (KASS):
* https://www.gps.gov/technical/prn-codes/L1-CA-PRN-code-assignments-2021-Jun.pdf
* https://www.airbus.com/en/newsroom/press-releases/2022-06-airbus-built-measat-3d-communications-satellite-ready-for-launch

I'll focus on fixing BDS in this issue because it's much simpler (the flag, etc. already exists) and save KASS for https://github.com/barbeau/gpstest/issues/598.

**Comment by barbeau** [comment]
Actually, BDS was already fixed in https://github.com/barbeau/gpstest/commit/08cb7b5cf8f01267399097fc0ff02829865d920f, so v3.10.0 (currently in beta) and higher should show BDS SBAS correctly. So I'm closing this as complete.
