### ISSUE TITLE
Option for input from NMEA log

### ISSUE THREAD

**Issue by abw8353** [barbeau/gpstest#641]
Could an option be added to take input from an NMEA log instead of the realtime device receiver? (I don't think I have missed this if it already exists)

This would be useful for investigating certain device or situational issues, as well as a path for testing external GNSS receivers. Potentially, it could be a stepping stone to supporting connected external GNSS receivers ( https://github.com/barbeau/gpstest/issues/79 )

**Comment by barbeau** [comment]
@abw8353 Thanks for the feedback! This is possible, but to be honest it would be a low priority compared to #79.

As a workaround you could replay an existing NMEA file via the Android emulator - see https://hussainhabibullah.medium.com/simulate-location-in-android-emulator-289fd6de0432.

For now, though, you would only see the location update - you wouldn't see the list of satellites on the Status screen.
