### ISSUE TITLE
force Android to use one GNSS ?

### ISSUE THREAD

**Issue by jlmxyz** [barbeau/gpstest#643]
Hi,
After moving out of samsung firmware to lineageOS, I don't see anymore glonass on gpstest, I don't know if it's a problem of lineageOS that I should report or if it's just that GPS, Galileo, beido are faster and then fill the available slots... 

gpstest has a filter, but it only filter the list, I don't know if Android allow to deactivate GNSS constellation to force use a constellation?

thanks and regards

**Comment by barbeau** [comment]
@jlmxyz tl;dr it's a lineageOS issue. The filter feature in GPSTest only hides certain satellites from view in the app - it doesn't have any impact on how your device uses those satellites. To my knowledge there isn't any simple way for developers to tell Android to only use a certain GNSS constellation.
