### ISSUE TITLE
Add support for Beidou-3 B2b signal

### ISSUE THREAD

**Issue by Narugakuruga** [barbeau/gpstest#652]
Mediatek Demisey 9200 add BDS-3 B2b and Galileo E5b signal supports.
B2b is broadcasted by all BDS-3 MEO/IGSO satellites (C19-C46) and PPP-B2b is broadcasted by BDS-3 GEO satellites (C59-C62).
Would be cool to see the new signal in action!

**Comment by Narugakuruga** [comment]
Would be nice to test it out ☺️. 
I will check with a phone with D9200+ chipset someday

**Comment by Narugakuruga** [comment]
I'm very curious to find out these Beidou-3 GEO satellites use B1l frequency for navigation service, B1C and B2a frequency for SBAS service. Their B2b is for high accuracy PPP measurement. 

While all these bands of other Beidou-3 sats is only for common navigation. 

So every GEO satellites serve 3 functions. That's interesting.

But right now the SBAS service is in test stage. Not for public use I think....

**Comment by Narugakuruga** [comment]
![image](https://github.com/barbeau/gpstest/assets/31060534/9afdcf0c-6a2e-4081-9f3f-71d2bca3cab1)
Screenshot with Redmi K60 Ultra (D9200+ Soc)

**Comment by Narugakuruga** [comment]
My test shows B2b is on 1207.14 MHz band. (Constellation type 5 for BDS right? )
Which is the old "B2/B2l" that gpstest already labeled. 
It's weird it doesn't shows up as B2 yet. 
![Screenshot_2023-10-05-23-41-10-681_com miui gallery-edit](https://github.com/barbeau/gpstest/assets/31060534/84c21e81-090d-44c9-a13b-f5891debf18c)

**Comment by Narugakuruga** [comment]
According to BDS official website.
B2b is expected to fully replace B2 as they use same 1207.14Mhz (maybe even un-interoperable too?)

**Comment by barbeau** [comment]
>My test shows B2b is on 1207.14 MHz band. (Constellation type 5 for BDS right? )

Nice! What device is the screenshot from?

**Comment by Narugakuruga** [comment]
Redmi K60 Ultra in China, aka Xiaomi 13T Pro :)
Maybe it's because android api couldn't report B2b signal? I guess.
So inside the GNSS chip it's using b2b to calculate location and PPP correction, but can't be read by android api?

**Comment by Narugakuruga** [comment]
In GNSSLoger, BDS's 1207.14 MHz only shows up in MeasurementProviderMeasurement. 
But it would not display in Status SATELLITE_STATUS

**Comment by Narugakuruga** [comment]
Ahh I see. Gnss logger can shows B2b normally.

Apparently mediatek 9200 chip only received B2b exclusively from 3 satellite. So it's easy to miss it.

Last time when I doing the measurement it was indoor, so I didn't receive the signal. 

So maybe Gpstest can show that too. We just have to rename B2 to B2b

![Screenshot_2023-10-24-15-31-00-352_com miui gallery-edit](https://github.com/barbeau/gpstest/assets/31060534/8eef780d-c7a6-4f48-9ff2-7c0cff459628)

**Comment by barbeau** [comment]
Closed by https://github.com/barbeau/gpstest/pull/657
