### ISSUE TITLE
Add support for NavIC L1 signal 

### ISSUE THREAD

**Issue by Narugakuruga** [barbeau/gpstest#653]
According to Indian Space Research Organization, 

“A new civilian signal is being introduced in L1 band(1575.42 MHz). All forthcoming (2023 onwards) NavIC satellites will broadcast SPS signals in L1, L5 and S bands”
(Source: https://www.isro.gov.in/SatelliteNavigationServices.html)

Appears that India want to support the mainstream GNSS device with L1 band.... 

![IMG_20230910_190745](https://github.com/barbeau/gpstest/assets/31060534/05847c04-4450-43e9-966a-dc468d3dbf84)

**Comment by barbeau** [comment]
Thanks for the info @Narugakuruga!

**Comment by Narugakuruga** [comment]
closed by #657
