### ISSUE TITLE
More Compact Satellite Frequency status

### ISSUE THREAD

**Issue by Narugakuruga** [barbeau/gpstest#656]
### Reason behind
As every GNSS constellation is using more frequency than ever before, the Satellite status page is kinda of bloated. 
For every 1 satellite, there can be up to 4 frequency to show up
For example Beidou B1/B1C/B2a/B2b
Galileo E1/E5a/E5b/E6
GPS L1/L2/L5
And there are already phones that support all the signal above (except E6).
![image](https://github.com/barbeau/gpstest/assets/31060534/4d5acb0f-ec62-48a2-85f3-b2994129dace)

### My suggestion
Idea 1
The easy way to reduce the visual clearness is, only show one ID for every physical satellite? It works when every satellite has the same frequency, and the interval between is just neat. But when SF and DF sats line up together it look like trash....

![未标题-1](https://github.com/barbeau/gpstest/assets/31060534/2d5464e0-8b3e-4e53-b82a-c375611e234d)

Idea 2
maybe we can compress the whole satellite, make the UI something like this?
but the CNR has no space to show. What if we use color to represent CNR,
for good signal above 35db, it will be pure green. For 30 to 34.9db it will be Brown green, and 20 to 29.9db yellow. And red below 20, and so forth.
But will require some coding.... I wish I could contribute if I can do coding.
 
Forgive my Photoshop technique😀 it's very rough idea. 
![未标题-2](https://github.com/barbeau/gpstest/assets/31060534/c7ad6e3e-1117-4398-8963-fcf51598159b)

**Comment by barbeau** [comment]
Yes, this is a tough one. The Filter and Sort features help with this, but the list does get long.

I've been working on a Dashboard feature I hope to release in the near future that is focused on more summary-level info that may help fill this gap:
https://github.com/barbeau/gpstest/pull/570

**Comment by barbeau** [comment]
Closing this in favor of https://github.com/barbeau/gpstest/pull/570
