### ISSUE TITLE
Not listing any satellites

### ISSUE THREAD

**Issue by skyper-cz** [barbeau/gpstest#661]
**Describe the bug**
When I start app, the counter of satellites is zero even after I get time list is also open.

**To Reproduce**
1. Open app
2. Thats it

**Expected behavior**
See number and list of satellites

**Observed behavior**
Seing zero satellites and empty list.

**App, Device and Android version:** 

App: 4.10.1-3
Device: Huawei P60 Art
OS: HarmonyOS 4.0

**Screenshots:** 

![Screenshot_20231202_210521_com.android.gpstest.osmdroid.jpg](https://github.com/barbeau/gpstest/assets/62872636/c5ba31b9-b48b-4a33-b2dc-7828670b5f2c)

**Comment by barbeau** [comment]
Thanks for the report! Seems like the entire GnssStatus API is broken on this device. Is this the operating system the shipped with the device, or a custom ROM?

Either way, I don't think there is much I can do about this. You'd need to report it to the device manufacturer or the ROM maintainers.
