### ISSUE TITLE
Detecting GNSS Jamming and Spoofing on Android Devices

### ISSUE THREAD

**Issue by draekko** [barbeau/gpstest#667]
**Is your feature request related to a problem? Please describe.**
Not related to a problem yet 

**Describe the solution you'd like**
it would be nice Gpstest implemented a jamming or spoofing attack visual signal to know when either situation arises as per the research paper description below.

**Additional context**
Articles/Papers

"Detecting GNSS Jamming and Spoofing on Android Devices"
DOI: https://doi.org/10.33012/navi.537
https://navi.ion.org/content/69/3/navi.537

"Improving GNSS Spoofing Awareness in
Smartphones via Statistical Processing
of Raw Measurements"
DOI:  10.1109/OJCOMS.2023.3260905
https://ieeexplore.ieee.org/stamp/stamp.jsp?arnumber=10081330

**Comment by barbeau** [comment]
Thanks @draekko, this is definitely something I'm interesting in, but just haven't had the time to tackle. I already have #231 open for this feature, so I've copied your references to that issue. Any more references you find are welcome!
