### ISSUE TITLE
Swiping away the persistent background GNSS notification should do the same thing as pressing stop

### ISSUE THREAD

**Issue by altayhunter** [barbeau/gpstest#675]
**Is your feature request related to a problem? Please describe.**
My primary use case for GPSTest is to use it to force my GPS to run in the background (with Run GNSS in background checked) so that I can get Google Maps to collect data for my Location History. I'll simply open GPSTest, then switch to a different app or turn my screen off, and can count on it running in the background. When I want to stop it I'll open my notifications drawer, swipe open the GPSTest notification, then press Stop.
This works pretty well, but the Stop button is pretty small and sometimes I'll accidentally tap elsewhere in the notification, which causes it to bring up the app instead of closing it. Then I have to swipe down and try again.

**Describe the solution you'd like**
Swiping the notification away should do the same thing as pressing the Stop button. Currently it just momentarily dismisses the notification, which reappears a second later.

**Describe alternatives you've considered**
N/A

**Additional context**
![Screenshot_20240216-183356](https://github.com/barbeau/gpstest/assets/871691/f30b6c7d-9863-47a5-b5f6-501f4100e0f6)

**Comment by barbeau** [comment]
@altayhunter Thanks for the feedback! So the behavior of persistent notifications is different on different devices. On some (most?) devices the persistent notification can't be swiped away. Also, Android requires a persistent notification when tracking location - so I need to leave the existing implementation as-is.
