### ISSUE TITLE
L5 satellites no shown on new smartphone Infinix hot 50

### ISSUE THREAD

**Issue by aliandwa** [barbeau/gpstest#695]
Hello! L5 satellites no shown on new smartphone Infinix hot 50. OS Android 14, CPU Mediatek Helio G100, which can work with GPS / QZSS L1+ L5 / Galileo E1 + E5a / BeiDou B1C + B2a / NAVIC. Accuracy in GPSTest is reportet as 1.2-1.4 meters. Is it bug or f feature? :)
![Screenshot_20241113-100429 1](https://github.com/user-attachments/assets/a1e22433-7e8b-492d-a04a-462f60496ac1)

**Comment by barbeau** [comment]
@aliandwa Thanks for the report! 

Could you please open an issue at https://b.corp.google.com/issues/new?component=313183&template=1021001 with this screenshot, and include a log with measurements and status too? 

Please post the link here after opening the issue.

I'm going to close this, as there isn't anything to be done on the GPSTest app.
