### ISSUE TITLE
Status SignalCount and SignalIndex field values are swapped in GPSTest 3.10.3

### ISSUE THREAD

**Issue by smartnorman** [barbeau/gpstest#696]
**Describe the bug**
When GNSS Status is logged by GPSTest 3.10.3, the values of SignalCount and SignalIndex fields are swapped, so SignalCount actually contains the SignalIndex value, SignalIndex contains the SignalCount value.  I confirmed this by logging Status on the same Android unit using GPSTest 3.10.3, which shows the problem, and GNSSLogger (3.0.6.3 and 3.1.0.3 on different Android devices), which has the values in the correct fields.

**To Reproduce**
1. Work in a location which has good GNSS signal
2. Run GPSTest
3. Turn on logging of GNSSStatus
4. After a few minutes turn off GNSSStatus logging
5. Transfer the log file to PC and examine Log file Status using Excel or whatever method you choose

**Expected behavior**
- The SignalCount field should be the same for all records in an epoch
- The SignalIndex field for records in one epoch should have values from 0 to SignalCount-1

**Observed behavior**
- The SignalCount field has values from 0 to SignalIndex-1
- The SignalIndex field has the same value for all records in an epoch

**App, Device and Android version:** 
Tested using GPSTest v3.10.3, comparitive files also collected using GNSSLogger 3.0.6.3 and 3.1.0.3
One device is a Trimble prototype Android handheld with Android 14 (engineering build)
Second device is Nokia 7Plus with standard Android 10 OS

**Screenshots:** 
Not relevant - this is a GNSS Log file issue

**Log Files**
GNSS Log files for GPSTest and GNSSLogger are attached.
[Nokia7Plus-GPSTest-gnss_log_2024_11_29_11_45_59.csv](https://github.com/user-attachments/files/17952754/Nokia7Plus-GPSTest-gnss_log_2024_11_29_11_45_59.csv)
[Nokia7Plus-GNSSLogger-gnss_log_2024_11_29_11_44_27.csv](https://github.com/user-attachments/files/17952755/Nokia7Plus-GNSSLogger-gnss_log_2024_11_29_11_44_27.csv)

**Comment by barbeau** [comment]
@smartnorman Thanks for the report, good catch!
