### ISSUE TITLE
terminology issue +- conceptual issue: "your location" on accuracy page

### ISSUE THREAD

**Issue by JohnDenker** [barbeau/gpstest#702]
Background:
The Accuracy page makes use of what I call the **Reference Point** as indicated by the red teardrop-shaped waypoint symbol. So far so good.

Unfortunately, in several places that app refers to this as "your real location" or "your latitude" or "your longitude".

This is a terminology issue, of the type that can lead to conceptual errors, as we can see from the following:

Use case: I'm sitting in the comfort of my lab, typing in the coordinates of the **Reference Point** ... which could be miles away from my "real location".

Use case: I might no know what the **Reference Point** looks like until I find it. I use the GPS help me find it. So the coordinates I enter could not possibly be my "real location".

Use case: I know of some benchmarks, emplaced and surveyed by the National Geodetic Survey, which no longer exist. The coordinates represent a point in space, but they are not the "real" location of anything.

Therefore: Suggestion: Change the terminology in the Edit box on the Accuracy page so it refers to the **Reference Point** (not "your" anything and not "real" anything).

Similarly, change the label on the red waypoint on the Accuracy map.

Tangential remark: To further illustrate the distinction between "your location" and the **Reference Point**, it would be nice to have a button (perhaps on the Edit popup) that would warp the Accuracy page **Reference Point** to the current GPS location. I will file a feature request on this.

**Comment by barbeau** [comment]
Thanks for the feedback! My assumption is that the majority of users are running this in the field, and not all are familiar with GPS/GNSS/GIS terminology, in which case IMHO the "real" location terminology is easier to understand. I'm open to more feedback if others think this needs to be changed, but closing for now.
