### ISSUE TITLE
Add flag for GAGAN

### ISSUE THREAD

**Issue by kanchudeep** [barbeau/gpstest#92]
[GPS Aided GEO Augmented Navigation](https://en.wikipedia.org/wiki/GPS_Aided_GEO_Augmented_Navigation) (GAGAN) satellites (PRN 127, 128, 139) in the listing are shown without a corresponding country flag.

Request add flag of India in the listing to ease identification of the satellite(s)/constellation.

Note: Refer the attached screenshot and notice no flag with PRN 127.

![screenshot_20170902-194333](https://user-images.githubusercontent.com/30999796/29998284-94eb182c-9044-11e7-9e77-7cd05ce61429.png)

**Comment by barbeau** [comment]
Thanks @kanchudeep! Yes, I can add Gagan. What mobile device (make and model) is the screenshot from, and what is the Android version?

**Comment by kanchudeep** [comment]
Welcome @barbeau...
The above screenshot is on a OnePlus 5 running Nougat (7.1.1).
GAGAN satellites are also listed on my other following devices:

1. Asus/Google Nexus 7 (2013) running Marshmallow (6.0.1).
2. Samsung S2+ running custom AOSP Marshmallow (6.0.1) based ROM.
3. Asus/Google Nexus 7C (2012) running Lollipop (5.1.1).

If you want I can also send you the ADB logcats...

Also, I'm in India and have observed these satellites in both Northern and Eastern part of the country.

**Comment by barbeau** [comment]
@kanchudeep Can you please send screenshots for the other devices too?  If you could turn on NMEA logging via "Settings->NMEA" and send logs that would be great.

One question - how do you know that the PRN range is 127, 127, and 139?  Have you seen all three of these on your devices?

**Comment by kanchudeep** [comment]
@barbeau, I'll get the screenshots, NMEA logs and attach.

As for PRN refer:
![](http://www.isac.gov.in/navigation/images/gagan.png)
(Original page http://www.isac.gov.in/navigation/gagan.jsp)
GSAT-8 is marked as PRN127 and GSAT-10 as PRN128.
GSAT-15 (captioned as in-orbit spare) is not marked with any PRN No.

https://www.pulsesat.com/satellites/s/02d3cd67-dff7-4517-935c-9201cdbb3909/ and https://www.celestrak.com/NORAD/elements/sbas.txt states the PRN as 139.
There are some conflicting sources which state the PRN as 132, but I'm more inclined towards 139.

I'll try and see if I get either PRN 132 or 139. I do remember catching 127 and 128 distinctively (in fact just before taking the screenshot in the first post).

I'm the developer of an Android navigation app [Deesha](https://play.google.com/store/apps/details?id=com.deeppradhan.deesha2) and as one of it tools it gives information on GNSS satellites, so I have been researching with different devices and GNSS satellites. So most of this information on GAGAN is based on that research/experience.

**Comment by barbeau** [comment]
@kanchudeep If you're just able to provide screenshots of all the GAGAN PRNs you can see from your device, that should be enough for me to implement this (don't worry about logs, etc).  I'd like to get it out in the next version.

**Comment by kanchudeep** [comment]
@barbeau, sorry I have been busy...

The GAGAN SVs seen on OnePlus 5:
![gagan-oneplus-5](https://user-images.githubusercontent.com/30999796/30782962-00a8317e-a159-11e7-8df4-43b67b75ef0d.png)

The GAGAN SVs seen on Nexus 7 (2013):
![gagan-nexus-7-2013](https://user-images.githubusercontent.com/30999796/30782964-1980a79e-a159-11e7-839c-4fc2d5bc9b2d.png)
**Note**: The Nexus 7 (2013) seems to report NMEA IDs instead of PRN. You need to add 87 to get the PRN from the NMEA IDs.

I have not been able to observe either PRN132 or PRN139 of GSAT-15.

**Comment by barbeau** [comment]
@kanchudeep I've published a new release including GAGAN and the Indian flag (v2.2.0) to the beta channel, which you can either sign up for [here](https://github.com/barbeau/gpstest/blob/master/BETA_TESTING.md#register-as-a-beta-tester) or just download the APK directly from Github at https://github.com/barbeau/gpstest/releases/tag/v2.2.0.

Could you please give this a try and let me know if you see the Indian flag now?

Screenshots welcome :).

**Comment by kanchudeep** [comment]
Greetings...

Sorry, I didn't get time to check earlier.

Attaching a screenshot.
It is displaying Indian flag correctly for GSAT-8/PRN 127.

Regards...
दीप प्रधान

**Comment by barbeau** [comment]
@kanchudeep Thanks! Could you post screenshot again? It didn't attach last time.

**Comment by kanchudeep** [comment]
Greetings...

Screenshot attached again.

One issue I think I might have noticed. The last flag seems to be cropped from the bottom. I see this with the Indian flag in this screenshot and also noticed with some other flags.

Regards...
दीप प्रधान

**Comment by barbeau** [comment]
If you're attaching via email I don't believe that works - you need to add from desktop web view.
