### ISSUE TITLE
Add country flags to Help or Readme?

### ISSUE THREAD

**Issue by goldfndr** [barbeau/gpstest#96]
Could the country flags be added to the Help or the Readme?

Some people might not have the looks of particular country's flags memorized (yet). Adding the country flags to the Help or Readme, along with the country name and the name of the GNSS and SBAS constellation each represented, would help educate people rather than having them try to somehow look up the images. It would also be a method to "show off" all the satellite sources the installed version of GPS Test supports.

**Comment by barbeau** [comment]
Thanks, I'll look at this. Definitely a good idea but more cosmetic items have just been towards the bottom of the TODO list.

**Comment by barbeau** [comment]
Flags and names are now shown in the Legend in the Sky view, so I'm closing this.
