### ISSUE TITLE
Add What's New? to menu

### ISSUE THREAD

**Issue by goldfndr** [barbeau/gpstest#97]
Could you add a menu item to popup What's New? to the menu?

It'd been a while since I'd installed 2.1.11 and, since I didn't spot an announcement of what had changed in the Google Group, I was curious as to what changes had been made. I was unable to find a method to bring up this popup after first run.

It'd be a helpful way to jog one's memory down the road.

**Comment by barbeau** [comment]
Thanks - yes, I can add this.
