### ISSUE TITLE
Document Sky non-SNR color

### ISSUE THREAD

**Issue by goldfndr** [barbeau/gpstest#99]
Could you add a line to the Help text documenting the non-SNR color?

Currently, the Help text only mentions ranges of colors from red to green (actually lime green?) for specific values of SNR and C/N0.

I looked at the sky view and saw the different colors and wondered what they represented. I looked at the Help text and eventually saw that they represented different ranges of SNR. (I say eventually because the colors are somewhat hidden in the text.) I went back and saw a few near the border of the view that didn't appear to have a color between red and green. I had to go back to the Status tab to discover that they didn't have SNR values.

It would be helpful to document the color used by non-SNR satellites. I suggest text of "(color) is used for satellites that lack a SNR or CN/0 value."

 (Optional addition: these lines documenting the colors are complete sentences, and thus should have a period at the end. It's somewhat of a pet peeve of mine (spread by a former coworker) that complete sentences in list items should end with periods.)

**Comment by barbeau** [comment]
Sure, this should be easy enough to add. On my TODO list is to add a key or show colors in Help, but that requires a bit more work, related to #96.
